REVOKE ALL PRIVILEGES ON DATABASE dataspace_test FROM public;
REVOKE ALL PRIVILEGES ON DATABASE dataspace_dev FROM public;
REVOKE ALL PRIVILEGES ON DATABASE dataspace_prod FROM public;

DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'app_python') THEN

      RAISE NOTICE 'Role "app_python" already exists. Skipping.';
   ELSE
      CREATE ROLE app_python LOGIN CREATEDB;
   END IF;
END
$do$;

-- Allow app_python impersonate sonum (to restart sequences)
GRANT sonum TO app_python WITH SET TRUE;

GRANT CONNECT ON DATABASE dataspace_test, dataspace_dev, dataspace_prod TO app_python;

CREATE SCHEMA IF NOT EXISTS import;

GRANT USAGE ON SCHEMA import TO app_python;

ALTER DEFAULT PRIVILEGES IN SCHEMA import GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO app_python;


CREATE TABLE import.ac_aidants (
    id integer,
    last_login timestamp without time zone,
    email character varying,
    first_name character varying,
    last_name character varying,
    is_active boolean,
    can_create_mandats boolean,
    date_joined timestamp without time zone,
    profession character varying,
    organisation_id integer,
    serial_number character varying,
    action character varying,
    date_last_action timestamp without time zone
);


CREATE TABLE import.ac_mandats (
    id integer,
    organisation_id integer,
    usager_id integer,
    creation_date timestamp without time zone,
    expiration_date timestamp without time zone,
    duree_keyword character varying,
    is_remote boolean,
    template_path character varying,
    remote_constent_method character varying,
    consent_request_id integer
);


CREATE TABLE import.ac_structures (
    id integer,
    name character varying,
    siret character varying,
    address character varying,
    zip_code character varying,
    type_id integer,
    data_pass_id integer,
    is_active boolean,
    city character varying,
    city_code character varying,
    department_code character varying,
    is_experiment boolean,
    france_services_label boolean,
    france_services_number character varying,
    uuid character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    legal_cat_level_one character varying,
    legal_cat_level_three character varying,
    legal_cat_level_two character varying,
    legal_category integer,
    siren character varying,
    allowed_demarches character varying
);


CREATE TABLE import.cn_conseillers (
    id character varying,
    id_pg integer,
    prenom character varying,
    nom character varying,
    email character varying,
    telephone character varying,
    distancemax integer,
    disponible boolean,
    date_disponibilite timestamp without time zone,
    est_demandeuremploi boolean,
    est_enemploi boolean,
    est_enformation boolean,
    est_diplomemednum boolean,
    nomdiplomemednum character varying,
    auneexperiencemednum boolean,
    codepostal character varying(5),
    location_type character varying,
    location_coordinates_0 character varying,
    location_coordinates_1 character varying,
    nomcommune character varying,
    codecommune character varying(5),
    codedepartement character varying(3),
    coderegion character varying(3),
    emailconfirmedat timestamp without time zone,
    emailconfirmationkey character varying,
    unsubscribedat timestamp without time zone,
    createdat timestamp without time zone,
    updatedat timestamp without time zone,
    importedat timestamp without time zone,
    deletedat character varying,
    usercreated character varying,
    pix_partage character varying,
    pix_datepartage timestamp without time zone,
    pix_palier character varying,
    pix_competence1 character varying,
    pix_competence2 character varying,
    pix_competence3 character varying,
    sondagesentat character varying,
    codecom character varying,
    sondagetoken character varying,
    datefinformation timestamp without time zone,
    datepriseposte timestamp without time zone,
    estrecrute boolean,
    statut character varying,
    structureid character varying,
    mattermost_error character varying,
    mattermost_id character varying,
    mattermost_login character varying,
    mattermost_hubjoined character varying,
    mattermost_errorresetpassword character varying,
    emailcn_address character varying,
    emailcnerror character varying,
    datedenaissance timestamp without time zone,
    sexe character varying,
    groupecra character varying,
    groupecrahistorique_0_numero character varying,
    groupecrahistorique_1_numero character varying,
    groupecrahistorique_2_numero character varying,
    groupecrahistorique_0_datedechangement timestamp without time zone,
    groupecrahistorique_1_datedechangement timestamp without time zone,
    groupecrahistorique_2_datedechangement timestamp without time zone,
    groupecrahistorique_0_nbjourdansgroupe character varying,
    groupecrahistorique_1_nbjourdansgroupe character varying,
    telephonepro character varying,
    emailpro character varying,
    suphierarchique_numerotelephone character varying,
    suphierarchique_email character varying,
    suphierarchique_nom character varying,
    suphierarchique_prenom character varying,
    suphierarchique_fonction character varying,
    haspermanence boolean,
    coderegionstructure character varying(3),
    codedepartementstructure character varying(3),
    certifie boolean,
    mailactivitecramois character varying,
    certificationpixformation character varying,
    resetpasswordcnerror character varying,
    coordinateurs_0_id character varying,
    coordinateurs_1_id character varying,
    coordinateurs_0_nom character varying,
    coordinateurs_1_nom character varying,
    coordinateurs_0_prenom character varying,
    coordinateurs_1_prenom character varying,
    coordinateurs_0_nonaffichagecarto character varying,
    coordinateurs_1_nonaffichagecarto character varying,
    "groupeCRAHistorique_0_dateMailSendConseillerM+1" timestamp without time zone,
    "groupeCRAHistorique_2_dateMailSendConseillerM+1" timestamp without time zone,
    "groupeCRAHistorique_1_dateMailSendConseillerM+1" timestamp without time zone,
    "groupeCRAHistorique_0_mailSendConseillerM+1" character varying,
    "groupeCRAHistorique_2_mailSendConseillerM+1" character varying,
    "groupeCRAHistorique_1_mailSendConseillerM+1" character varying,
    "groupeCRAHistorique_0_dateMailSendStructureM+1" timestamp without time zone,
    "groupeCRAHistorique_2_dateMailSendStructureM+1" timestamp without time zone,
    "groupeCRAHistorique_1_dateMailSendStructureM+1" timestamp without time zone,
    "groupeCRAHistorique_0_mailSendStructureM+1" character varying,
    "groupeCRAHistorique_2_mailSendStructureM+1" character varying,
    "groupeCRAHistorique_1_mailSendStructureM+1" character varying,
    "groupeCRAHistorique_0_dateMailSendConseillerM+1.5" timestamp without time zone,
    "groupeCRAHistorique_2_dateMailSendConseillerM+1.5" timestamp without time zone,
    "groupeCRAHistorique_1_dateMailSendConseillerM+1.5" timestamp without time zone,
    "groupeCRAHistorique_0_mailSendConseillerM+1.5" character varying,
    "groupeCRAHistorique_2_mailSendConseillerM+1.5" character varying,
    "groupeCRAHistorique_1_mailSendConseillerM+1.5" character varying,
    "groupeCRAHistorique_0_dateMailSendStructureM+1.5" timestamp without time zone,
    "groupeCRAHistorique_2_dateMailSendStructureM+1.5" timestamp without time zone,
    "groupeCRAHistorique_1_dateMailSendStructureM+1.5" timestamp without time zone,
    "groupeCRAHistorique_0_mailSendStructureM+1.5" character varying,
    "groupeCRAHistorique_2_mailSendStructureM+1.5" character varying,
    "groupeCRAHistorique_1_mailSendStructureM+1.5" character varying,
    ruptures_0_structureid character varying,
    ruptures_1_structureid character varying,
    ruptures_2_structureid character varying,
    ruptures_0_daterupture timestamp without time zone,
    ruptures_1_daterupture timestamp without time zone,
    ruptures_2_daterupture timestamp without time zone,
    ruptures_0_motifrupture character varying,
    ruptures_1_motifrupture character varying,
    ruptures_2_motifrupture character varying,
    emailcn_deletemailboxcnerror character varying,
    mattermost_errordeleteaccount character varying,
    "groupeCRAHistorique_2_dateMailSendSupHierarchiqueM+1" timestamp without time zone,
    "groupeCRAHistorique_1_dateMailSendSupHierarchiqueM+1" timestamp without time zone,
    "groupeCRAHistorique_0_dateMailSendSupHierarchiqueM+1" timestamp without time zone,
    "groupeCRAHistorique_2_mailSendSupHierarchiqueM+1" character varying,
    "groupeCRAHistorique_1_mailSendSupHierarchiqueM+1" character varying,
    "groupeCRAHistorique_0_mailSendSupHierarchiqueM+1" character varying,
    "groupeCRAHistorique_2_dateMailSendSupHierarchiqueM+1.5" timestamp without time zone,
    "groupeCRAHistorique_1_dateMailSendSupHierarchiqueM+1.5" timestamp without time zone,
    "groupeCRAHistorique_0_dateMailSendSupHierarchiqueM+1.5" timestamp without time zone,
    "groupeCRAHistorique_2_mailSendSupHierarchiqueM+1.5" character varying,
    "groupeCRAHistorique_1_mailSendSupHierarchiqueM+1.5" character varying,
    "groupeCRAHistorique_0_mailSendSupHierarchiqueM+1.5" character varying,
    c_file character varying,
    c_extension character varying,
    c_date timestamp without time zone,
    usercreationerror character varying,
    estcoordinateur boolean,
    listesubordonnes_type character varying,
    listesubordonne_liste_0 character varying,
    listesubordonne_liste_1 character varying,
    listesubordonne_liste_2 character varying,
    listesubordonne_liste_3 character varying,
    listesubordonne_liste_4 character varying,
    listesubordonne_liste_5 character varying,
    listesubordonne_liste_6 character varying,
    listesubordonne_liste_7 character varying,
    listesubordonne_liste_8 character varying,
    listesubordonne_liste_9 character varying,
    listesubordonne_liste_10 character varying,
    listesubordonne_liste_11 character varying,
    listesubordonne_liste_12 character varying,
    listesubordonne_liste_13 character varying,
    listesubordonne_liste_14 character varying,
    listesubordonne_liste_15 character varying,
    listesubordonne_liste_16 character varying,
    listesubordonne_liste_17 character varying,
    listesubordonne_liste_18 character varying,
    listesubordonne_liste_19 character varying,
    listesubordonne_liste_20 character varying,
    listesubordonne_liste_21 character varying,
    listesubordonne_liste_22 character varying,
    listesubordonne_liste_23 character varying,
    listesubordonne_liste_24 character varying,
    listesubordonne_liste_25 character varying,
    listesubordonne_liste_26 character varying,
    listesubordonne_liste_27 character varying,
    listesubordonne_liste_28 character varying,
    listesubordonne_liste_29 character varying,
    listesubordonne_liste_30 character varying,
    listesubordonne_liste_31 character varying,
    listesubordonne_liste_32 character varying,
    listesubordonne_liste_33 character varying,
    listesubordonne_liste_34 character varying,
    listesubordonne_liste_35 character varying,
    listesubordonne_liste_36 character varying,
    listesubordonne_liste_37 character varying,
    mailproamodifier character varying,
    tokenchangementmailpro character varying,
    tokenchangementmailprocreatedat character varying,
    mailconfirmerror character varying,
    mailconfirmerrordetail character varying,
    mattermost_errorpatchlogin character varying,
    historique_0_data_ancienemail character varying,
    historique_0_data_nouveauemail character varying,
    historique_0_date timestamp without time zone,
    mailamodifier character varying,
    tokenchangementmail character varying,
    tokenchangementmailcreatedat timestamp without time zone,
    unsubscribeextras_comment character varying,
    unsubscribeextras_is_useful character varying,
    nonaffichagecarto character varying,
    emailcn_emailcnerror character varying,
    "groupeCRAHistorique_2_mailErrorDetailStructureM+1" character varying,
    "groupeCRAHistorique_2_mailErrorStructureM+1" character varying,
    ruptureerror character varying
);


CREATE TABLE import.cn_cras (
    id character varying,
    canal character varying,
    activite character varying,
    nbparticipants integer,
    age_moins12ans integer,
    age_de12a18ans integer,
    age_de18a35ans integer,
    age_de35a60ans integer,
    age_plus60ans integer,
    statut_etudiant integer,
    statut_sansemploi integer,
    statut_enemploi integer,
    statut_retraite integer,
    statut_heterogene integer,
    themes_0 character varying,
    themes_1 character varying,
    themes_2 character varying,
    themes_3 character varying,
    themes_4 character varying,
    themes_5 character varying,
    themes_6 character varying,
    themes_7 character varying,
    themes_8 character varying,
    themes_9 character varying,
    themes_10 character varying,
    themes_11 character varying,
    themes_12 character varying,
    duree character varying,
    accompagnement_individuel integer,
    accompagnement_atelier integer,
    accompagnement_redirection integer,
    codepostal character varying(5),
    nomcommune character varying,
    dateaccompagnement timestamp without time zone,
    codecommune character varying(5),
    organismes character varying,
    conseiller character varying,
    createdat timestamp without time zone,
    structure character varying,
    nbparticipantsrecurrents character varying,
    permanence character varying,
    updatedat timestamp without time zone,
    fixupdatedat timestamp without time zone,
    sousthemes_0_annotation character varying,
    sousthemes_1_annotation character varying,
    organismes_0_ccas character varying,
    sousthemes_0_equipement_informatique_0 character varying,
    sousthemes_0_equipement_informatique_1 character varying,
    sousthemes_0_accompagner_enfant character varying
);


CREATE TABLE import.cn_permanences (
    id character varying,
    eststructure boolean,
    nomenseigne character varying,
    numerotelephone character varying,
    email character varying,
    siteweb character varying,
    siret character varying,
    adresse_numerorue character varying,
    adresse_rue character varying,
    adresse_codepostal character varying(5),
    adresse_ville character varying,
    adresse_codecommune character varying(5),
    location_type character varying,
    location_coordinates_0 real,
    location_coordinates_1 real,
    horaires_0_matin_0 character varying,
    horaires_0_matin_1 character varying,
    horaires_1_matin_0 character varying,
    horaires_1_matin_1 character varying,
    horaires_2_matin_0 character varying,
    horaires_2_matin_1 character varying,
    horaires_3_matin_0 character varying,
    horaires_3_matin_1 character varying,
    horaires_4_matin_0 character varying,
    horaires_4_matin_1 character varying,
    horaires_5_matin_0 character varying,
    horaires_5_matin_1 character varying,
    horaires_6_matin_0 character varying,
    horaires_6_matin_1 character varying,
    horaires_0_apresmidi_0 character varying,
    horaires_0_apresmidi_1 character varying,
    horaires_1_apresmidi_0 character varying,
    horaires_1_apresmidi_1 character varying,
    horaires_2_apresmidi_0 character varying,
    horaires_2_apresmidi_1 character varying,
    horaires_3_apresmidi_0 character varying,
    horaires_3_apresmidi_1 character varying,
    horaires_4_apresmidi_0 character varying,
    horaires_4_apresmidi_1 character varying,
    horaires_5_apresmidi_0 character varying,
    horaires_5_apresmidi_1 character varying,
    horaires_6_apresmidi_0 character varying,
    horaires_6_apresmidi_1 character varying,
    typeacces_0 character varying,
    typeacces_1 character varying,
    typeacces_2 character varying,
    conseillers_0 character varying,
    conseillers_1 character varying,
    conseillers_2 character varying,
    conseillers_3 character varying,
    conseillers_4 character varying,
    conseillers_5 character varying,
    conseillers_6 character varying,
    conseillers_7 character varying,
    conseillers_8 character varying,
    conseillers_9 character varying,
    lieuprincipalpour_0 character varying,
    lieuprincipalpour_1 character varying,
    lieuprincipalpour_2 character varying,
    lieuprincipalpour_3 character varying,
    lieuprincipalpour_4 character varying,
    lieuprincipalpour_5 character varying,
    lieuprincipalpour_6 character varying,
    lieuprincipalpour_7 character varying,
    lieuprincipalpour_8 character varying,
    structure character varying,
    updatedat timestamp without time zone,
    updatedby character varying,
    conseillersitinerants_0 character varying,
    conseillersitinerants_1 character varying
);


CREATE TABLE import.cn_relations (
    id character varying,
    distance real,
    statut character varying,
    conseillerobj_id character varying,
    structureobj_id character varying,
    datedebutdecontrat timestamp without time zone,
    datefindecontrat timestamp without time zone,
    typedecontrat character varying,
    reconventionnement boolean,
    miseenrelationreconventionnement character varying
);


CREATE TABLE import.cn_structures (
    id character varying NOT NULL,
    statut character varying NOT NULL,
    nom character varying NOT NULL,
    siret character varying,
    "date_Debut_Mission" timestamp without time zone,
    "created_At" timestamp without time zone,
    "est_ZRR" boolean,
    "qpv_Statut" character varying,
    insee_activite_principale_code character varying,
    insee_activite_principale_libelle character varying,
    insee_tranche_effectif_salarie_intitule character varying,
    insee_unite_legale_rna character varying,
    insee_unite_legale_forme_juridique_libelle character varying,
    insee_adresse_numero_voie numeric,
    insee_adresse_indice_repetition_voie character varying,
    insee_adresse_type_voie character varying,
    insee_adresse_libelle_voie character varying,
    insee_adresse_code_postal character varying,
    insee_adresse_libelle_commune character varying,
    insee_adresse_code_commune character varying
);

CREATE TABLE import.carto (
    id character varying NOT NULL,
    structure_coop_id UUID,
    pivot character varying(14) NOT NULL,
    nom character varying NOT NULL,
    commune character varying NOT NULL,
    code_postal character varying(5) NOT NULL,
    code_insee character varying(5),
    adresse character varying NOT NULL,
    complement_adresse character varying,
    latitude real,
    longitude real,
    adresse_sirene character varying,
    typologie character varying,
    telephone character varying,
    courriels character varying,
    site_web character varying,
    horaires character varying,
    presentation_resume character varying,
    presentation_detail character varying,
    source character varying,
    itinerance character varying,
    structure_parente character varying,
    date_maj date NOT NULL,
    services character varying,
    publics_specifiquement_adresses character varying,
    prise_en_charge_specifique character varying,
    frais_a_charge character varying,
    dispositif_programmes_nationaux character varying,
    formations_labels character varying,
    autres_formations_labels character varying,
    modalites_acces character varying,
    modalites_accompagnement character varying,
    fiche_acces_libre character varying,
    prise_rdv character varying,
    etat_administratif varchar(255) DEFAULT NULL,
    code_activite_principale character varying(6) DEFAULT NULL,
    categorie_juridique character varying(4) DEFAULT NULL,
    denomination_sirene character varying DEFAULT NULL,
    ban_clef_interop varchar(30),
    ban_code_ban uuid,
    ban_longitude real,
    ban_latitude real,
    ban_numero smallint,
    ban_repetition varchar(10),
    ban_voie character varying,
    ban_ville character varying,
    ban_code_postal varchar(5),
    ban_code_insee varchar(5)
);
