CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION unaccent;

-- Functions
CREATE OR REPLACE FUNCTION updated_at_column() RETURNS TRIGGER AS $$
  BEGIN
    NEW.updated_at = now();
    RETURN NEW;
  END;
  $$ LANGUAGE plpgsql;


CREATE TABLE import.ign_region (
    id CHARACTER VARYING(24) NOT NULL,
    geom GEOMETRY (MULTIPOLYGON, 4326) NOT NULL,
    nom_m CHARACTER VARYING(35) NOT NULL,
    nom CHARACTER VARYING(35) NOT NULL,
    insee_reg CHARACTER VARYING(2) NOT NULL
);

CREATE TABLE import.ign_departement (
    id CHARACTER VARYING(24) NOT NULL,
    geom GEOMETRY (MULTIPOLYGON, 4326) NOT NULL,
    nom_m CHARACTER VARYING(30) NOT NULL,
    nom CHARACTER VARYING(30) NOT NULL,
    insee_dep CHARACTER VARYING(3) NOT NULL,
    insee_reg CHARACTER VARYING(2) NOT NULL
);

CREATE TABLE import.ign_epci (
    id CHARACTER VARYING(24),
    geom GEOMETRY (MULTIPOLYGON, 4326) NOT NULL,
    code_siren CHARACTER VARYING(9),
    nom CHARACTER VARYING(230),
    nature CHARACTER VARYING(150)
);

CREATE TABLE import.ign_commune (
    id CHARACTER VARYING(24) NOT NULL,
    geom GEOMETRY (MULTIPOLYGON, 4326) NOT NULL,
    nom CHARACTER VARYING(50) NOT NULL,
    nom_m CHARACTER VARYING(50) NOT NULL,
    insee_com CHARACTER VARYING(5) NOT NULL,
    statut CHARACTER VARYING(26) NOT NULL,
    population INTEGER NOT NULL,
    insee_can CHARACTER VARYING(5) NOT NULL,
    insee_arr CHARACTER VARYING(2) NOT NULL,
    insee_dep CHARACTER VARYING(3) NOT NULL,
    insee_reg CHARACTER VARYING(2) NOT NULL,
    siren_epci CHARACTER VARYING(20)
);

CREATE TABLE import.ign_arrondissement (
    id CHARACTER VARYING(24) NOT NULL,
    geom GEOMETRY (MULTIPOLYGON, 4326) NOT NULL,
    nom CHARACTER VARYING(50) NOT NULL,
    nom_m CHARACTER VARYING(50) NOT NULL,
    insee_arm CHARACTER VARYING(5) NOT NULL,
    insee_com CHARACTER VARYING(5) NOT NULL,
    population INTEGER NOT NULL
);

CREATE TABLE import.insee_mvt_comm (
    mod SMALLINT NOT NULL,
    date_eff DATE NOT NULL,
    typecom_av CHARACTER VARYING(4),
    com_av CHARACTER VARYING(5),
    tncc_av CHARACTER VARYING(1),
    ncc_av CHARACTER VARYING(50),
    nccenr_av CHARACTER VARYING(50),
    libelle_av CHARACTER VARYING(50),
    typecom_ap CHARACTER VARYING(4) NOT NULL,
    com_ap CHARACTER VARYING(5) NOT NULL,
    tncc_ap CHARACTER VARYING(1) NOT NULL,
    ncc_ap CHARACTER VARYING(50) NOT NULL,
    nccenr_ap CHARACTER VARYING(50) NOT NULL,
    libelle_ap CHARACTER VARYING(50) NOT NULL
);

CREATE TABLE import.laposte_insee_cp (
    code_insee CHARACTER VARYING(5) NOT NULL,
    nom_com CHARACTER VARYING(50) NOT NULL,
    code_postal CHARACTER VARYING(5) NOT NULL,
    lib_achem CHARACTER VARYING(50) NOT NULL,
    lieu_dit CHARACTER VARYING(50)
);


CREATE SCHEMA admin;

GRANT USAGE ON SCHEMA admin TO app_python;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT SELECT ON TABLES TO xxx;
ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO app_python;
ALTER DEFAULT PRIVILEGES IN SCHEMA admin GRANT USAGE, UPDATE ON SEQUENCES TO app_python;


CREATE TABLE admin.region (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    geom GEOMETRY (MULTIPOLYGON, 4326) NOT NULL,
    code CHARACTER VARYING(2) NOT NULL,
    nom CHARACTER VARYING(35) NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT region_pkey PRIMARY KEY (id),
    CONSTRAINT region_ukey UNIQUE (code)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON admin.region FOR EACH ROW EXECUTE FUNCTION updated_at_column();

CREATE TABLE admin.departement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    geom GEOMETRY (MULTIPOLYGON, 4326) NOT NULL,
    region_id INTEGER NOT NULL,
    code CHARACTER VARYING(3) NOT NULL,
    nom CHARACTER VARYING(30) NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT departement_pkey PRIMARY KEY (id),
    CONSTRAINT departement_ukey UNIQUE (code),
    CONSTRAINT departement_region_id FOREIGN KEY (region_id) REFERENCES admin.region (id)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON admin.departement FOR EACH ROW EXECUTE FUNCTION updated_at_column();

CREATE TABLE admin.epci (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    geom GEOMETRY (MULTIPOLYGON, 4326) NOT NULL,
    code CHARACTER VARYING(9) NOT NULL,
    type CHARACTER VARYING(32) NOT NULL,
    nom CHARACTER VARYING(90) NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT epci_pkey PRIMARY KEY (id),
    CONSTRAINT epci_ukey UNIQUE (code)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON admin.epci FOR EACH ROW EXECUTE FUNCTION updated_at_column();

CREATE TABLE admin.commune (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    geom GEOMETRY (MULTIPOLYGON, 4326) NOT NULL,
    departement_id INTEGER NOT NULL,
    statut CHARACTER VARYING(24),
    code_insee CHARACTER VARYING(5) NOT NULL,
    nom CHARACTER VARYING(50) NOT NULL,
    population INTEGER,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT commune_pkey PRIMARY KEY (id),
    CONSTRAINT commune_ukey UNIQUE (code_insee),
    CONSTRAINT commune_departement_id FOREIGN KEY (departement_id) REFERENCES admin.departement (id)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON admin.commune FOR EACH ROW EXECUTE FUNCTION updated_at_column();

CREATE INDEX commune_nom_idx ON admin.commune USING btree (nom);
CREATE INDEX commune_geom_idx ON admin.commune USING gist (geom);


CREATE TABLE admin.commune_epci (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    commune_id INTEGER NOT NULL,
    epci_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT commune_epci_pkey PRIMARY KEY (id),
    CONSTRAINT commune_epci_ukey UNIQUE (commune_id, epci_id),
    CONSTRAINT commune_epci_commune_id FOREIGN KEY (commune_id) REFERENCES admin.commune (id),
    CONSTRAINT commune_epci_epci_id FOREIGN KEY (epci_id) REFERENCES admin.epci (id)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON admin.commune_epci FOR EACH ROW EXECUTE FUNCTION updated_at_column();


CREATE TABLE admin.insee_historique (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    code_insee_ancien CHARACTER VARYING(5) NOT NULL,
    code_insee_nouveau CHARACTER VARYING(5) NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT insee_historique_pkey PRIMARY KEY (id),
    CONSTRAINT insee_historique_ukey UNIQUE (code_insee_ancien, code_insee_nouveau)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON admin.insee_historique FOR EACH ROW EXECUTE FUNCTION updated_at_column();

COMMENT ON TABLE admin.insee_historique IS 'Table d''historisation des modifications des codes INSEE (création, suppression, fusion etc. des communes).';
COMMENT ON COLUMN admin.insee_historique.code_insee_ancien IS 'Ancien code INSEE.';
COMMENT ON COLUMN admin.insee_historique.code_insee_nouveau IS 'Nouveau code INSEE.';

CREATE TABLE admin.insee_cp (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    code_insee CHARACTER VARYING(5) NOT NULL,
    code_postal CHARACTER VARYING(5) NOT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT insee_cp_pkey PRIMARY KEY (id),
    CONSTRAINT insee_cp_ukey UNIQUE (code_postal, code_insee)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON admin.insee_cp FOR EACH ROW EXECUTE FUNCTION updated_at_column();

CREATE TABLE admin.zonage (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    geom GEOMETRY (MULTIPOLYGON, 4326) DEFAULT NULL,
    code CHARACTER VARYING(8),
    libelle CHARACTER VARYING(255),
    code_insee CHARACTER VARYING(5) NOT NULL,
    type CHARACTER VARYING(3) NOT NULL,
    commentaire TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT zonage_pkey PRIMARY KEY (id),
    CONSTRAINT zonage_qpv_ukey UNIQUE (code, code_insee),
    CONSTRAINT zonage_code_insee_fkey FOREIGN KEY (code_insee) REFERENCES admin.commune (code_insee)
);

CREATE INDEX zonage_code_insee_idx ON admin.zonage USING btree (code_insee);
CREATE INDEX zonage_geom_idx ON admin.zonage USING gist (geom);
CREATE UNIQUE INDEX zonage_frr_ukey ON admin.zonage (code_insee) where type = 'FRR';

CREATE TRIGGER updated_at BEFORE UPDATE ON admin.zonage FOR EACH ROW EXECUTE FUNCTION updated_at_column();

COMMENT ON TABLE admin.zonage IS 'Table de gestion des zonages administratifs FRR et QPV.';
COMMENT ON COLUMN admin.zonage.code IS 'Identifiant unique du zonage concerne QPV uniquement - généré par l''API.';
COMMENT ON COLUMN admin.zonage.libelle IS 'Libelle du zonage concerne QPV uniquement - généré par l''API.';
COMMENT ON COLUMN admin.zonage.type IS 'Type de zonage (QPV: Quartier Prioritaire de la Ville, FRR: France Ruralités Revitalisation).';
COMMENT ON COLUMN admin.zonage.commentaire IS 'Commentaire sur le zonage - généré par l''API.';



CREATE TABLE admin.ifn_commune (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    code_insee CHARACTER VARYING(5) NOT NULL,
    score NUMERIC NOT NULL,
    -- date DATE DEFAULT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT ifn_commune_pkey PRIMARY KEY (id),
    CONSTRAINT ifn_commune_ukey UNIQUE (code_insee/*, date*/)
);

-- Create index on code_insee
CREATE INDEX ifn_commune_code_insee_idx ON admin.ifn_commune USING btree (code_insee/*, date*/);

CREATE TRIGGER updated_at BEFORE UPDATE ON admin.ifn_commune FOR EACH ROW EXECUTE FUNCTION updated_at_column();

COMMENT ON TABLE admin.ifn_commune IS 'Table des Indices de Fragilité Numérique communaux : https://fragilite-numerique.fr/.';
COMMENT ON COLUMN admin.ifn_commune.code_insee IS 'Code INSEE de la commune.';
COMMENT ON COLUMN admin.ifn_commune.score IS 'Valeur de 0 à 10 indiquant l''indice de fragilité numérique de la commune. Cette valeur est la somme de plusieurs indicateurs, pour plus d''informations : https://infos.fragilite-numerique.fr/ressources-cgu.';


CREATE TABLE admin.ifn_departement (
    id INTEGER GENERATED BY default AS IDENTITY,
    code CHARACTER VARYING(3) NOT NULL,
    score NUMERIC NOT NULL,
    -- date DATE DEFAULT NULL,
    created_at TIMESTAMP DEFAULT now(),
    updated_at timestamp DEFAULT NULL,
    CONSTRAINT ifn_departement_pkey PRIMARY KEY (id),
    CONSTRAINT ifn_departement_code_dept_unique UNIQUE (code/*, date*/)
);

-- Create index on code column
CREATE INDEX ifn_departement_code_dept_idx ON admin.ifn_departement USING btree (code/*, date*/);

-- Create trigger for updated_at
CREATE TRIGGER admin_ifn_departement_updated_at BEFORE UPDATE ON admin.ifn_departement FOR EACH ROW EXECUTE PROCEDURE updated_at_column();

-- Add description to ifn_commune table
COMMENT ON TABLE admin.ifn_departement IS 'Table de gestion des départements IFN - Indice de Fragilité Numérique : https://fragilite-numerique.fr/';

COMMENT ON COLUMN admin.ifn_departement.code IS 'Code département : un code à 2 ou 3 chiffres qui identifie le département français, en métropole ou en outre-mer. Par exemple, "13" pour les Bouches-du-Rhône.';
COMMENT ON COLUMN admin.ifn_departement.score IS 'Score : Un nombre réel qui varie de [0 - 10] indiquant l''indice de fragilité numérique du département. cette valeur est une somme totale de plusieurs indicateurs, pour plus d''informations, voir le site : https://infos.fragilite-numerique.fr/ressources-cgu';


CREATE MATERIALIZED VIEW admin.coll_terr AS (
    SELECT
        region.id AS region_id,
        region.code AS region_code,
        region.nom AS region_nom,
        departement.id AS departement_id,
        departement.code AS departement_code,
        departement.nom AS departement_nom,
        -- epci.code AS epci_code,
        -- epci.type AS epci_type,
        -- epci.nom AS epci_nom,
        commune.id AS commune_id,
        commune.code_insee,
        commune.nom AS commune_nom
    FROM admin.commune AS commune
    -- LEFT JOIN admin.commune_epci AS commune_epci ON commune.id = commune_epci.commune_id
    -- LEFT JOIN admin.epci AS epci ON commune_epci.epci_id = epci.id
    LEFT JOIN admin.departement AS departement ON commune.departement_id = departement.id
    LEFT JOIN admin.region AS region ON departement.region_id = region.id
);

COMMENT ON MATERIALIZED VIEW admin.coll_terr IS 'Table de regroupement des territoires (région, département, EPCI, commune) hors EPCI.';

-- Nota: Certaines communes appartiennent à plusieurs EPCI.


CREATE OR REPLACE FUNCTION admin.refresh_coll_terr() RETURNS VOID AS $$
BEGIN
    REFRESH MATERIALIZED VIEW admin.coll_terr;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION admin.refresh_coll_terr IS 'Fonction permettant de rafraichir la MV admin.coll_terr sans droits de propriétaire';

GRANT EXECUTE ON FUNCTION admin.refresh_coll_terr() TO app_python;
