DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE rolname = 'app_api') THEN

      RAISE NOTICE 'Role "app_api" already exists. Skipping.';
   ELSE
      CREATE ROLE app_api LOGIN;
   END IF;
END
$do$;

GRANT CONNECT ON DATABASE dataspace_prod TO app_api;

--
-- Schema public
--

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM app_api;
REVOKE ALL ON SCHEMA public FROM app_api;



-- Functions
CREATE OR REPLACE FUNCTION updated_at_column() RETURNS TRIGGER AS $$
  BEGIN
    NEW.updated_at = now();
    RETURN NEW;
  END;
  $$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION updated_at_column TO app_python;


--
-- Schema main
--

CREATE SCHEMA main;

GRANT USAGE ON SCHEMA main TO app_python;
GRANT SELECT, INSERT, UPDATE, TRUNCATE, TRIGGER ON ALL TABLES IN SCHEMA main TO app_python;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA main TO app_python
ALTER DEFAULT PRIVILEGES IN SCHEMA main GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO app_python;
ALTER DEFAULT PRIVILEGES IN SCHEMA main GRANT USAGE ON SEQUENCES TO app_python;


CREATE TABLE main.adresse (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    geom GEOMETRY (POINT, 4326) NULL,
    clef_interop CHARACTER VARYING(50),
    code_ban UUID DEFAULT NULL,
    departement CHARACTER VARYING(3),
    code_postal CHARACTER VARYING(5),
    code_insee CHARACTER VARYING(5),
    nom_commune CHARACTER VARYING(255),
    nom_voie CHARACTER VARYING(255),
    repetition VARCHAR(10),
    numero_voie SMALLINT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT adresse_pkey PRIMARY KEY (id),
    CONSTRAINT adresse_code_ban_ukey UNIQUE (code_ban)
);

CREATE UNIQUE INDEX adresse_ukey ON main.adresse (code_postal, nom_commune, nom_voie, coalesce(numero_voie, 0), coalesce(repetition, ''));

CREATE INDEX adresse_code_insee_idx ON main.adresse USING btree (code_insee);
CREATE INDEX adresse_geom_idx ON main.adresse USING gist (geom);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.adresse FOR EACH ROW EXECUTE FUNCTION updated_at_column();


CREATE TABLE main.structure (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    structure_coop_id UUID,
    structure_ac_id UUID,
    structure_tp_id INTEGER,
    nom CHARACTER VARYING(255) NOT NULL,
    denomination_sirene CHARACTER VARYING,
    siret CHARACTER VARYING(14),
    rna CHARACTER VARYING(10),
    adresse_id INTEGER,
    contact JSONB,
    etat_administratif CHARACTER VARYING,
    code_activite_principale CHARACTER VARYING(6),
    categorie_juridique CHARACTER VARYING(4) DEFAULT NULL,
    nb_mandats_ac INTEGER,
    publique BOOLEAN,
    structure_cartographie_nationale_id CHARACTER VARYING,
    visible_pour_cartographie_nationale BOOLEAN,
    typologies TEXT[],
    presentation_resume TEXT,
    presentation_detail TEXT,
    horaires CHARACTER VARYING,
    prise_rdv CHARACTER VARYING,
    structure_parente UUID,
    services TEXT[],
    publics_specifiquement_adresses TEXT[],
    prise_en_charge_specifique TEXT[],
    frais_a_charge TEXT[],
    dispositif_programmes_nationaux TEXT[],
    formations_labels TEXT[],
    autres_formations_labels TEXT[],
    itinerance TEXT[],
    modalites_acces TEXT[],
    modalites_accompagnement TEXT[],
    mediateurs_en_activite INTEGER,
    emplois INTEGER,
    source CHARACTER VARYING,
    fiche_acces_libre CHARACTER VARYING,
    last_sirene_enrich_at DATE DEFAULT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT structure_pkey PRIMARY KEY (id),
    CONSTRAINT structure_cartographie_ukey UNIQUE (structure_cartographie_nationale_id),
    CONSTRAINT structure_siret_format_check CHECK (siret ~ '^\d{14}$'),
    CONSTRAINT structure_structure_coop_id_ukey UNIQUE (structure_coop_id),
    CONSTRAINT structure_structure_ac_id_ukey UNIQUE (structure_ac_id),
    CONSTRAINT structure_structure_tp_id_ukey UNIQUE (structure_tp_id),
    CONSTRAINT structure_adresse_fkey FOREIGN KEY (adresse_id) REFERENCES main.adresse (id),
    CONSTRAINT structure_categorie_juridique_fkey FOREIGN KEY (categorie_juridique) REFERENCES reference.categories_juridiques (code)
);

CREATE UNIQUE INDEX structure_nom_ukey ON main.structure (siret, nom, COALESCE(adresse_id, 0));

CREATE TRIGGER updated_at BEFORE UPDATE ON main.structure FOR EACH ROW EXECUTE FUNCTION updated_at_column();


CREATE TABLE main.personne (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    prenom CHARACTER VARYING(50),
    nom CHARACTER VARYING(50),
    contact JSONB,
    structure_id INTEGER,
    aidant_connect_id INTEGER,
    conseiller_numerique_id CHARACTER VARYING(50),
    cn_pg_id INTEGER,
    coop_id UUID,
    is_coordinateur BOOLEAN,
    is_mediateur BOOLEAN,
    is_active_ac BOOLEAN,
    formation_fne_ac BOOLEAN,
    profession_ac CHARACTER VARYING,
    nb_accompagnements_ac INTEGER,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT personne_pkey PRIMARY KEY (id),
    CONSTRAINT personne_coop_id_ukey UNIQUE (coop_id),
    CONSTRAINT personne_aidant_connect_id_ukey UNIQUE (aidant_connect_id),
    CONSTRAINT personne_conseiller_numerique_id_ukey UNIQUE (conseiller_numerique_id),
    CONSTRAINT personne_cn_pg_id_ukey UNIQUE (cn_pg_id),
    CONSTRAINT personne_structure_id_fkey FOREIGN KEY (structure_id) REFERENCES main.structure (id)
);

CREATE INDEX personne_patronyme ON main.personne USING btree (nom, prenom);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.personne FOR EACH ROW EXECUTE FUNCTION updated_at_column();


CREATE TABLE main.formation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    personne_id INTEGER NOT NULL,
    -- Les champs de la formation
    label CHARACTER VARYING(11),
    parcours CHARACTER VARYING(4),
    lot SMALLINT,
    marche_formation CHARACTER VARYING(8),
    lieu CHARACTER VARYING(255),
    -- Les dates
    date_debut DATE,
    date_fin DATE,
    -- certifications
    pix BOOLEAN,
    remn BOOLEAN,
    observations TEXT,
    created_at TIMESTAMP DEFAULT now(),
    updated_at TIMESTAMP DEFAULT NULL,
    CONSTRAINT formation_pkey PRIMARY KEY (id),
    CONSTRAINT formation_parcours_check CHECK (parcours IN ('70h', '175h', '315h', '105h', '420h', '280h', '350h')),
    CONSTRAINT formation_label_check CHECK (label IN ('CCP1', 'CCP2', 'CCP2 & CCP3')),
    CONSTRAINT formation_personne_id_fkey FOREIGN KEY (personne_id) REFERENCES main.personne (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX formation_personne_id_idx ON main.formation (personne_id);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.formation FOR EACH ROW EXECUTE PROCEDURE updated_at_column();

COMMENT ON TABLE main.formation IS 'Table de gestion des formations des Conseillers Numériques.';
COMMENT ON COLUMN main.formation.label IS 'Label de la formation, exemple : CCP1, CCP2, CCP2 & CCP3';
COMMENT ON COLUMN main.formation.parcours IS 'Parcours de formation défini après un test de positionnement : débutant (315h), intermédiaire (175h), ou avancé (70h).';


-- Table des activités
CREATE TABLE main.activites_coop (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    coop_id UUID,
    structure_id INTEGER,
    personne_id INTEGER,
    type CHARACTER VARYING(100) NOT NULL,
    date DATE NOT NULL,
    duree INT NOT NULL,
    lieu_code_insee CHARACTER VARYING(5),
    type_lieu CHARACTER VARYING(100) NOT NULL,
    autonomie CHARACTER VARYING(100),
    structure_de_redirection character varying(255),
    oriente_vers_structure BOOLEAN,
    precisions_demarche TEXT,
    degre_de_finalisation_demarche CHARACTER VARYING(50),
    titre_atelier CHARACTER VARYING(255),
    niveau_atelier CHARACTER VARYING(50),
    accompagnements INT NOT NULL DEFAULT 0,
    thematiques TEXT[],
    materiels TEXT[],
    thematiques_demarche_administrative TEXT[],
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT activites_coop_pkey PRIMARY KEY (id),
    CONSTRAINT activites_coop_coop_id_ukey UNIQUE (coop_id),
    CONSTRAINT activites_coop_personne_id_fkey FOREIGN KEY (personne_id) REFERENCES main.personne (id),
    CONSTRAINT activites_coop_structure_id_fkey FOREIGN KEY (structure_id) REFERENCES main.structure (id)--,
    -- CONSTRAINT activites_coop_lieu_code_insee_fkey FOREIGN KEY (lieu_code_insee) REFERENCES admin.commune (code_insee)
);

CREATE INDEX activites_coop_lieu_code_insee_idx ON main.activites_coop (lieu_code_insee);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.activites_coop FOR EACH ROW EXECUTE FUNCTION updated_at_column();

COMMENT ON COLUMN main.activites_coop.duree IS 'Valeur en minutes';


CREATE TABLE main.poste (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    poste_conum_id INTEGER NOT NULL,
    structure_id INTEGER,
    personne_id INTEGER,
    etat_instruction CHARACTER VARYING(30),
    typologie CHARACTER VARYING(6) CHECK (typologie IN ('conum', 'coordo', 'dns')),
    date_attribution DATE NOT NULL,
    date_rendu_poste DATE,
    poste_renouvele BOOLEAN,
    action_coselec CHARACTER VARYING(255),
    origine_transfert INTEGER,
    etat CHARACTER VARYING(6) CHECK (etat IN ('vacant', 'occupe', 'rendu')),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT poste_pkey PRIMARY KEY (id),
    CONSTRAINT poste_ukey UNIQUE (poste_conum_id, structure_id, personne_id),
    CONSTRAINT poste_check CHECK (NOT (etat = 'rendu' AND date_rendu_poste IS NULL)),
    CONSTRAINT poste_structure_id_fkey FOREIGN KEY (structure_id) REFERENCES main.structure (id),
    CONSTRAINT poste_personne_id_fkey FOREIGN KEY (personne_id) REFERENCES main.personne (id)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.poste FOR EACH ROW EXECUTE FUNCTION updated_at_column();


CREATE TABLE main.contrat (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    personne_id INTEGER NOT NULL,
    date_debut DATE,
    date_fin DATE DEFAULT NULL,
    date_rupture DATE DEFAULT NULL,
    type CHARACTER VARYING(3),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT contrat_pkey PRIMARY KEY (id),
    CONSTRAINT contrat_type_check CHECK (type IN ('CDD', 'CDI', 'CDP', 'PEC')),
    CONSTRAINT contrat_personne_id_fkey FOREIGN KEY (personne_id) REFERENCES main.personne (id)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.contrat FOR EACH ROW EXECUTE FUNCTION updated_at_column();


CREATE TABLE main.coordination_mediation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    coordinateur_id integer NOT NULL,
    mediateur_id integer NOT NULL,
    coordinateur_coop_id UUID NOT NULL,
    mediateur_coop_id UUID NOT NULL,
    en_cours BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT coordination_mediation_pkey PRIMARY KEY (id),
    CONSTRAINT coordination_mediation_coodinateur_id_fkey FOREIGN KEY (coordinateur_id) REFERENCES main.personne (id),
    CONSTRAINT coordination_mediation_mediateur_id_fkey FOREIGN KEY (mediateur_id) REFERENCES main.personne (id),
    CONSTRAINT coordination_mediation_coordinateur_coop_id_fkey FOREIGN KEY (coordinateur_coop_id) REFERENCES main.personne (coop_id),
    CONSTRAINT coordination_mediation_mediateur_coop_id_fkey FOREIGN KEY (mediateur_coop_id) REFERENCES main.personne (coop_id)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.coordination_mediation FOR EACH ROW EXECUTE FUNCTION updated_at_column();

-- Table de lien entre les personnes et les structures employeuses.
CREATE TABLE main.personne_structures_emplois (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    personne_id INTEGER NOT NULL,
    structure_id INTEGER,
    structure_coop_id UUID,
    mediateur_coop_id UUID,
    en_cours BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT personne_structures_emplois_pkey PRIMARY KEY (id),
    CONSTRAINT personne_structures_emplois_personne_id_key FOREIGN KEY (personne_id) REFERENCES main.personne (id),
    -- CONSTRAINT personne_structures_emplois_structure_id_key FOREIGN KEY (structure_id) REFERENCES main.structure (id),
    -- CONSTRAINT personne_structures_emplois_structure_coop_id_key FOREIGN KEY (structure_coop_id) REFERENCES main.structure (structure_coop_id),
    CONSTRAINT personne_structures_emplois_mediateur_coop_id_key FOREIGN KEY (mediateur_coop_id) REFERENCES main.personne (coop_id)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.personne_structures_emplois FOR EACH ROW EXECUTE FUNCTION updated_at_column();

-- Table de lien entre les personnes et les structures et/ou lieux activités.
CREATE TABLE main.personne_lieux_activites (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    personne_id INTEGER NOT NULL,
    structure_id INTEGER,
    structure_coop_id UUID,
    mediateur_coop_id UUID,
    en_cours BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT personne_lieux_activites_pkey PRIMARY KEY (id),
    CONSTRAINT personne_lieux_activites_personne_id_fkey FOREIGN KEY (personne_id) REFERENCES main.personne (id),
    -- CONSTRAINT personne_lieux_activites_lieu_id_fkey FOREIGN KEY (structure_id) REFERENCES main.structure (id),
    -- CONSTRAINT personne_lieux_activites_lieu_id_coop_fkey FOREIGN KEY (structure_coop_id) REFERENCES main.structure (structure_coop_id),
    CONSTRAINT personne_lieux_activites_mediateur_coop_id_fkey FOREIGN KEY (mediateur_coop_id) REFERENCES main.personne (coop_id)
);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.personne_lieux_activites FOR EACH ROW EXECUTE FUNCTION updated_at_column();

CREATE TABLE main.subvention (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    poste_id INTEGER NOT NULL,
    source_financement CHARACTER VARYING(4),
    -- date des financements et conventions
    date_debut_convention DATE,
    date_debut_financement DATE,
    date_fin_convention DATE,
    date_fin_financement DATE,
    -- montants
    montant_subvention BIGINT,
    montant_bonification BIGINT,
    -- versements et montants
    versement_1 BIGINT,
    versement_2 BIGINT,
    versement_3 BIGINT,
    -- Date des versements
    date_versement_1 DATE,
    date_versement_2 DATE,
    date_versement_3 DATE,
    -- Informations sur la subvention
    is_territoire_prioritaire BOOLEAN,
    mois_utilises_periode_financement SMALLINT,
    mois_utilises_poste SMALLINT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT subvention_pkey PRIMARY KEY (id),
    CONSTRAINT subvention_source_check CHECK (source_financement IN ('DGCL', 'DGE', 'DITP')),
    CONSTRAINT subvention_poste_id_fkey FOREIGN KEY (poste_id) REFERENCES main.poste (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.subvention FOR EACH ROW EXECUTE FUNCTION updated_at_column();

-- Commentaires sur la table subvention
COMMENT ON COLUMN main.subvention.source_financement IS 'Origine des fonds reversés à la structure : DGCL (financement initial), DITP ou DGE (reconventionnement ou financement direct en phase 2)';
COMMENT ON COLUMN main.subvention.date_debut_convention IS 'Date de signature de la convention entre la structure employeuse et l’État. Marque le début de la relation contractuelle.';
COMMENT ON COLUMN main.subvention.date_fin_convention IS 'Date de fin prévisionnelle de la convention (généralement 2 à 3 ans après la signature, ajustée si des périodes de vacance existent).';
COMMENT ON COLUMN main.subvention.date_debut_financement IS 'Date du premier versement de subvention effectué à la structure (début effectif du financement).';
COMMENT ON COLUMN main.subvention.date_fin_financement IS 'Date de fin effective de la période de financement. En général, un an après le dernier versement sur le poste.';
COMMENT ON COLUMN main.subvention.montant_subvention IS 'Montant total de la subvention attribuée à la structure pour le poste concerné.';
COMMENT ON COLUMN main.subvention.montant_bonification IS 'Montant supplémentaire éventuellement accordé en complément de la subvention de base, attribuer en fonction de la priorité du territoire.';
COMMENT ON COLUMN main.subvention.is_territoire_prioritaire IS 'Indique si le poste subventionné se situe dans un territoire prioritaire au sens de la politique publique, Exemple : QPV (Quartiers Prioritaires de la Ville) ou FRR (France Ruralités Revitalisation) ';
COMMENT ON COLUMN main.subvention.mois_utilises_periode_financement IS 'Nombre de mois réellement consommés sur la période de financement allouée.';
