CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS api;

CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA auth;

CREATE TABLE auth.token(
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  token_id character varying(50) NOT NULL UNIQUE,
  pg_role character varying(50) NOT NULL,
  comment character varying(255) DEFAULT NULL,
  active boolean DEFAULT true NOT NULL,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone
);

CREATE TRIGGER token_updated_at BEFORE UPDATE ON auth.token FOR EACH ROW EXECUTE FUNCTION updated_at_column();

CREATE OR REPLACE FUNCTION auth.check_token() RETURNS void
  LANGUAGE plpgsql
  AS $$
DECLARE
  jwt_id TEXT := current_setting('request.jwt.claims', true)::json->>'jti';
  role TEXT := current_setting('request.jwt.claims', true)::json->>'aud';
BEGIN
  -- Vérifier si le token est révoqué ou absent
  IF NOT EXISTS (SELECT 1 FROM auth.token WHERE active IS TRUE AND token_id = jwt_id AND pg_role = role) AND current_user != 'postgrest_anonymous' THEN
    -- Lever l'exception pour bloquer l'exécution
    RAISE EXCEPTION 'Wrong token! Contact support.';
  END IF;
END;
$$;


CREATE OR REPLACE FUNCTION auth.url_encode(data bytea) RETURNS text LANGUAGE sql AS $$
    SELECT translate(encode(data, 'base64'), E'+/=\n', '-_');
$$ IMMUTABLE;


CREATE OR REPLACE FUNCTION auth.url_decode(data text) RETURNS bytea LANGUAGE sql AS $$
WITH t AS (SELECT translate(data, '-_', '+/') AS trans),
     rem AS (SELECT length(t.trans) % 4 AS remainder FROM t) -- compute padding size
    SELECT decode(
        t.trans ||
        CASE WHEN rem.remainder > 0
           THEN repeat('=', (4 - rem.remainder))
           ELSE '' END,
    'base64') FROM t, rem;
$$ IMMUTABLE;


CREATE OR REPLACE FUNCTION auth.algorithm_sign(signables text, secret text, algorithm text)
RETURNS text LANGUAGE sql AS $$
WITH
  alg AS (
    SELECT CASE
      WHEN algorithm = 'HS256' THEN 'sha256'
      WHEN algorithm = 'HS384' THEN 'sha384'
      WHEN algorithm = 'HS512' THEN 'sha512'
      ELSE '' END AS id)  -- hmac throws error
SELECT auth.url_encode(auth.hmac(signables, secret, alg.id)::bytea) FROM alg;
$$ IMMUTABLE;


CREATE OR REPLACE FUNCTION auth.sign(payload json, secret text, algorithm text DEFAULT 'HS256')
RETURNS text LANGUAGE sql AS $$
WITH
  header AS (
    SELECT auth.url_encode(convert_to('{"alg":"' || algorithm || '","typ":"JWT"}', 'utf8')) AS data
    ),
  payload AS (
    SELECT auth.url_encode(convert_to(payload::text, 'utf8')) AS data
    ),
  signables AS (
    SELECT header.data || '.' || payload.data AS data FROM header, payload
    )
SELECT
    signables.data || '.' ||
    auth.algorithm_sign(signables.data, secret, algorithm) FROM signables;
$$ IMMUTABLE;


CREATE OR REPLACE FUNCTION auth.verify(token text, secret text, algorithm text DEFAULT 'HS256')
RETURNS table(header json, payload json, valid boolean) LANGUAGE sql AS $$
  SELECT
    convert_from(auth.url_decode(r[1]), 'utf8')::json AS header,
    convert_from(auth.url_decode(r[2]), 'utf8')::json AS payload,
    r[3] = auth.algorithm_sign(r[1] || '.' || r[2], secret, algorithm) AS valid
  FROM regexp_split_to_array(token, '\.') r;
$$ IMMUTABLE;



CREATE OR REPLACE FUNCTION auth.create_jwt(token_id varchar(50), username varchar(50), expiration_date date, secret text) RETURNS text AS $$
  SELECT auth.sign(
    row_to_json(r), secret
  ) AS token
  FROM (
    SELECT
      token_id AS jti,
      username::text as aud,
      extract(epoch from expiration_date)::integer AS exp
  ) r;
$$ LANGUAGE sql;


-- Declare token in auth.token
CREATE OR REPLACE FUNCTION auth.add_token(token_id varchar(50), username varchar(50), comment varchar(50)) RETURNS VOID AS $$
  INSERT INTO auth.token (token_id, pg_role, comment)
  VALUES (token_id, username, comment)
  ON CONFLICT ON CONSTRAINT token_token_id_key DO NOTHING;
$$ LANGUAGE sql;

-- Meta function to create a new role and token
CREATE OR REPLACE FUNCTION auth.create_role_n_token(role_name character varying(50), role_description character varying(50), token_id character varying(50), postgrest_secret text, expiration_date date, token_description character varying(255) DEFAULT Null) RETURNS void
  LANGUAGE plpgsql
  AS $$
DECLARE
  jwt TEXT;
  BEGIN
    -- Create role
    IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = role_name) THEN

      RAISE NOTICE 'Role "%" already exists. Skipping.', role_name;
    ELSE
      EXECUTE format('CREATE ROLE %I NOLOGIN;
        COMMENT ON ROLE %I IS %L;',
        role_name, role_name, role_description);
    END IF;



  -- Allow app_api impersonate $role_name
  EXECUTE format('GRANT %I TO app_api', role_name);
  RAISE INFO 'Impersonation: ok';

  -- Need Usage on api schema to access to view(s)
  -- Need Usage on auth schema to access to table `token` and `check_token` function
  EXECUTE format('GRANT USAGE ON SCHEMA auth, api TO %I;
    GRANT EXECUTE ON FUNCTION auth.check_token TO %I;
    GRANT SELECT ON TABLE auth.token TO %I;',
    role_name, role_name, role_name);
  RAISE INFO 'Access: ok';

  -- Generate the JSON Web Token (l'id du token (permettant sa déactivation), PostgreSQL role, datetime d'expiration, 'le SECRET de PostgREST')
  EXECUTE format('
    SELECT auth.create_jwt(%L, %L, %L, %L)
    ', token_id, role_name, expiration_date, postgrest_secret)
    INTO jwt;
  RAISE NOTICE 'JWT: %s', jwt;

  -- Add the token declaration in `auth.token`
  EXECUTE format('
    SELECT auth.add_token(%L, %L, %L)', 
    token_id, role_name,  concat_ws(' ', token_description, 'Token valid until', (expiration_date::timestamp + INTERVAL '1 day - 1 microsecond')::timestamp));
  RAISE INFO 'Token authorization: ok';

  RAISE NOTICE 'Vous pouvez maintenant attribuer les droits sur la(les) table(s)/vue(s) au rôle %s;', role_name;

END;
$$;

COMMENT ON FUNCTION auth.create_role_n_token IS 'Création du rôle si inexistant puis création et activation du token.\nLes droits sur le(s) table(s)/vue(s) restent à attribuer.';


-- Pour Swagger
CREATE ROLE postgrest_anonymous NOLOGIN;
GRANT postgrest_anonymous TO app_api;

GRANT USAGE ON SCHEMA auth, api TO postgrest_anonymous;
GRANT EXECUTE ON FUNCTION auth.check_token TO postgrest_anonymous;
GRANT SELECT ON TABLE auth.token TO postgrest_anonymous;
