CREATE SCHEMA min;

CREATE EXTENSION pg_trgm;
CREATE EXTENSION citext WITH SCHEMA min;

GRANT USAGE ON SCHEMA min TO app_python;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA min TO app_python
ALTER DEFAULT PRIVILEGES IN SCHEMA min GRANT SELECT ON TABLES TO app_python;
ALTER DEFAULT PRIVILEGES IN SCHEMA min GRANT USAGE ON SEQUENCES TO app_python;


DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'min_scalingo') THEN

      RAISE NOTICE 'Role "min_scalingo" already exists. Skipping.';
   ELSE
      CREATE ROLE min_scalingo LOGIN CREATEDB;
      COMMENT ON ROLE min_scalingo IS 'Rôle applicatif pour MIN depuis Scalingo.';
   END IF;
END
$do$;

GRANT CONNECT ON DATABASE dataspace_test, dataspace_dev, dataspace_prod TO min_scalingo;


-- Usage on schemas
GRANT USAGE ON SCHEMA main, reference, admin, min TO min_scalingo;

-- Create on min dedicated schema
GRANT ALL ON SCHEMA min TO min_scalingo;

-- Select and references (foreign keys) on main, admin and reference tables
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA main, reference, admin TO min_scalingo;
ALTER DEFAULT PRIVILEGES IN SCHEMA main, reference, admin GRANT SELECT ON TABLES TO min_scalingo;

-- Need to read and write structures and adresses
GRANT SELECT, INSERT, UPDATE ON TABLE main.structure, main.adresse TO min_scalingo;
GRANT USAGE ON SEQUENCE main.structure_id_seq, main.adresse_id_seq TO min_scalingo;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA min TO min_scalingo
ALTER DEFAULT PRIVILEGES IN SCHEMA min GRANT ALL ON TABLES TO min_scalingo;
ALTER DEFAULT PRIVILEGES IN SCHEMA min GRANT ALL ON SEQUENCES TO min_scalingo;
GRANT ALL ON ALL TABLES IN SCHEMA min TO min_scalingo;
GRANT ALL ON ALL SEQUENCES IN SCHEMA min TO min_scalingo;


-- DEV users

DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'min_dev') THEN

      RAISE NOTICE 'Role "min_dev" already exists. Skipping.';
   ELSE
      CREATE ROLE min_dev NOLOGIN;
      COMMENT ON ROLE min_dev IS 'Rolegroup pour dev de l''équipe MIN.';
   END IF;
END
$do$;

GRANT CONNECT ON DATABASE dataspace_dev, dataspace_test TO min_dev;

-- Usage on schemas
GRANT USAGE ON SCHEMA main, reference, admin, min TO min_dev;

-- Create on min dedicated schema
GRANT CREATE ON SCHEMA min TO min_dev;

-- Select on main, admin and reference tables
GRANT SELECT ON ALL TABLES IN SCHEMA main, reference, admin TO min_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA main, reference, admin GRANT SELECT ON TABLES TO min_dev;

-- ALTER DEFAULT PRIVILEGES IN SCHEMA min TO min_scalingo
ALTER DEFAULT PRIVILEGES IN SCHEMA min GRANT ALL ON TABLES TO min_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA min GRANT ALL ON SEQUENCES TO min_dev;



--CREATE ROLE IF NOT EXISTS pmartinez LOGIN IN ROLE min_dev;
DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'pmartinez') THEN

      RAISE NOTICE 'Role "pmartinez" already exists. Skipping.';
   ELSE
      CREATE ROLE pmartinez LOGIN IN ROLE min_dev;
   END IF;
END
$do$;

--CREATE ROLE IF NOT EXISTS aturpin LOGIN IN ROLE min_dev;
DO
$do$
BEGIN
   IF EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'aturpin') THEN

      RAISE NOTICE 'Role "aturpinev" already exists. Skipping.';
   ELSE
      CREATE ROLE aturpin LOGIN IN ROLE min_dev;
   END IF;
END
$do$;



CREATE TYPE min."Role" AS ENUM (
    'administrateur_dispositif',
    'gestionnaire_departement',
    'gestionnaire_groupement',
    'gestionnaire_region',
    'gestionnaire_structure',
    'instructeur',
    'pilote_politique_publique',
    'support_animation'
);

ALTER TYPE min."Role" OWNER TO min_scalingo;


CREATE TABLE min._prisma_migrations (
    id character varying(36) NOT NULL,
    checksum character varying(64) NOT NULL,
    finished_at timestamp with time zone,
    migration_name character varying(255) NOT NULL,
    logs text,
    rolled_back_at timestamp with time zone,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    applied_steps_count integer DEFAULT 0 NOT NULL,
    CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
);

ALTER TABLE min._prisma_migrations OWNER TO min_scalingo;


CREATE TABLE min.region (
    code text NOT NULL,
    nom text NOT NULL,
    CONSTRAINT region_pkey PRIMARY KEY (code)
);

ALTER TABLE min.region OWNER TO min_scalingo;


CREATE TABLE min.departement (
    code text NOT NULL,
    region_code text NOT NULL,
    nom text NOT NULL,
    CONSTRAINT departement_pkey PRIMARY KEY (code),
    CONSTRAINT departement_region_code_fkey FOREIGN KEY (region_code) REFERENCES min.region(code) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE min.departement OWNER TO min_scalingo;


CREATE TABLE min.structure (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    adresse text NOT NULL,
    code_postal text NOT NULL,
    commune text NOT NULL,
    contact jsonb NOT NULL,
    departement_code text NOT NULL,
    identifiant_etablissement text NOT NULL,
    id_mongo text NOT NULL,
    nom min.citext NOT NULL,
    statut text NOT NULL,
    type text NOT NULL,
    CONSTRAINT structure_pkey PRIMARY KEY (id),
    CONSTRAINT structure_departement_code_fkey FOREIGN KEY (departement_code) REFERENCES min.departement(code) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE min.structure OWNER TO min_scalingo;


CREATE TABLE min.groupement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nom text NOT NULL,
    CONSTRAINT groupement_pkey PRIMARY KEY (id)
);

ALTER TABLE min.groupement OWNER TO min_scalingo;


CREATE TABLE min.utilisateur (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    date_de_creation timestamp(3) without time zone NOT NULL,
    departement_code text,
    derniere_connexion timestamp(3) without time zone,
    email_de_contact text NOT NULL,
    groupement_id integer,
    invite_le timestamp(3) without time zone NOT NULL,
    is_super_admin boolean DEFAULT false NOT NULL,
    is_supprime boolean DEFAULT false NOT NULL,
    nom min.citext NOT NULL,
    prenom text NOT NULL,
    region_code text,
    role min."Role" NOT NULL,
    structure_id integer,
    sso_id text DEFAULT ''::text NOT NULL,
    sso_email text NOT NULL,
    telephone character varying(13) NOT NULL,
    CONSTRAINT utilisateur_pkey PRIMARY KEY (id),
    CONSTRAINT utilisateur_sso_id_ukey UNIQUE (sso_id),
    CONSTRAINT utilisateur_sso_email_ukey UNIQUE (sso_email),
    CONSTRAINT utilisateur_departement_code_fkey FOREIGN KEY (departement_code) REFERENCES min.departement(code) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT utilisateur_groupement_id_fkey FOREIGN KEY (groupement_id) REFERENCES min.groupement(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT utilisateur_region_code_fkey FOREIGN KEY (region_code) REFERENCES min.region(code) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT utilisateur_structure_id_fkey FOREIGN KEY (structure_id) REFERENCES min.structure(id) ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE min.utilisateur OWNER TO min_scalingo;


CREATE TABLE min.gouvernance (
    departement_code text NOT NULL,
    note_privee jsonb,
    editeur_note_privee_id text,
    note_de_contexte text,
    editeur_note_de_contexte_id text,
    derniere_edition_note_de_contexte timestamp(3) without time zone,
    CONSTRAINT gouvernance_pkey PRIMARY KEY (departement_code),
    CONSTRAINT gouvernance_departement_code_fkey FOREIGN KEY (departement_code) REFERENCES min.departement(code) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT gouvernance_editeur_note_de_contexte_id_fkey FOREIGN KEY (editeur_note_de_contexte_id) REFERENCES min.utilisateur(sso_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT gouvernance_editeur_note_privee_id_fkey FOREIGN KEY (editeur_note_privee_id) REFERENCES min.utilisateur(sso_id) ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE min.gouvernance OWNER TO min_scalingo;


CREATE TABLE min.contact_membre_gouvernance (
    email text NOT NULL,
    prenom text NOT NULL,
    nom text NOT NULL,
    fonction text NOT NULL,
    CONSTRAINT contact_membre_gouvernance_pkey PRIMARY KEY (email)
);

ALTER TABLE min.contact_membre_gouvernance OWNER TO min_scalingo;


CREATE TABLE min.membre (
    id text NOT NULL,
    gouvernance_departement_code text NOT NULL,
    contact text NOT NULL,
    contact_technique text,
    type text,
    statut text NOT NULL,
    old_uuid uuid NOT NULL,
    is_coporteur boolean DEFAULT false NOT NULL,
    categorie_membre text,
    nom text,
    CONSTRAINT membre_pkey PRIMARY KEY (id),
    CONSTRAINT membre_contact_fkey FOREIGN KEY (contact) REFERENCES min.contact_membre_gouvernance(email) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT membre_contact_technique_fkey FOREIGN KEY (contact_technique) REFERENCES min.contact_membre_gouvernance(email) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT membre_gouvernance_departement_code_fkey FOREIGN KEY (gouvernance_departement_code) REFERENCES min.gouvernance(departement_code) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE min.membre OWNER TO min_scalingo;


CREATE TABLE min.feuille_de_route (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    gouvernance_departement_code text NOT NULL,
    creation timestamp(3) without time zone NOT NULL,
    nom text NOT NULL,
    piece_jointe text,
    porteur_id text,
    old_uuid uuid,
    derniere_edition timestamp(3) without time zone,
    editeur_utilisateur_id text,
    perimetre_geographique text,
    note_de_contextualisation text,
    CONSTRAINT feuille_de_route_pkey PRIMARY KEY (id),
    CONSTRAINT feuille_de_route_editeur_utilisateur_id_fkey FOREIGN KEY (editeur_utilisateur_id) REFERENCES min.utilisateur(sso_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT feuille_de_route_gouvernance_departement_code_fkey FOREIGN KEY (gouvernance_departement_code) REFERENCES min.gouvernance(departement_code) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT feuille_de_route_porteur_id_fkey FOREIGN KEY (porteur_id) REFERENCES min.membre(id) ON UPDATE CASCADE ON DELETE SET NULL
);

ALTER TABLE min.feuille_de_route OWNER TO min_scalingo;


CREATE TABLE min.action (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    besoins text[],
    createur_id integer NOT NULL,
    nom text NOT NULL,
    contexte text NOT NULL,
    description text NOT NULL,
    budget_global double precision NOT NULL,
    feuille_de_route_id integer NOT NULL,
    date_de_debut timestamp(3) without time zone NOT NULL,
    date_de_fin timestamp(3) without time zone NOT NULL,
    creation timestamp(3) without time zone NOT NULL,
    derniere_modification timestamp(3) without time zone NOT NULL,
    CONSTRAINT action_pkey PRIMARY KEY (id),
    CONSTRAINT action_createur_id_fkey FOREIGN KEY (createur_id) REFERENCES min.utilisateur(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT action_feuille_de_route_id_fkey FOREIGN KEY (feuille_de_route_id) REFERENCES min.feuille_de_route(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE min.action OWNER TO min_scalingo;


CREATE TABLE min.co_financement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_action integer NOT NULL,
    id_membre text NOT NULL,
    montant double precision NOT NULL,
    CONSTRAINT co_financement_pkey PRIMARY KEY (id),
    CONSTRAINT co_financement_id_action_fkey FOREIGN KEY (id_action) REFERENCES min.action(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT co_financement_id_membre_fkey FOREIGN KEY (id_membre) REFERENCES min.membre(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE min.co_financement OWNER TO min_scalingo;


CREATE TABLE min.comite (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    gouvernance_departement_code text NOT NULL,
    creation timestamp(3) without time zone NOT NULL,
    derniere_edition timestamp(3) without time zone NOT NULL,
    type text NOT NULL,
    frequence text NOT NULL,
    commentaire text,
    date timestamp(3) without time zone,
    editeur_utilisateur_id text NOT NULL,
    CONSTRAINT comite_pkey PRIMARY KEY (id),
    CONSTRAINT comite_editeur_utilisateur_id_fkey FOREIGN KEY (editeur_utilisateur_id) REFERENCES min.utilisateur(sso_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT comite_gouvernance_departement_code_fkey FOREIGN KEY (gouvernance_departement_code) REFERENCES min.gouvernance(departement_code) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE min.comite OWNER TO min_scalingo;


CREATE TABLE min.enveloppe_financement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    libelle text NOT NULL,
    date_debut timestamp(3) without time zone NOT NULL,
    date_fin timestamp(3) without time zone NOT NULL,
    montant double precision NOT NULL,
    CONSTRAINT enveloppe_financement_pkey PRIMARY KEY (id)
);

ALTER TABLE min.enveloppe_financement OWNER TO min_scalingo;


CREATE TABLE min.demande_de_subvention (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    createur_id integer NOT NULL,
    statut text NOT NULL,
    subvention_demandee double precision NOT NULL,
    subvention_etp double precision,
    subvention_prestation double precision,
    action_id integer NOT NULL,
    enveloppe_financement_id integer NOT NULL,
    creation timestamp(3) without time zone NOT NULL,
    derniere_modification timestamp(3) without time zone NOT NULL,
    CONSTRAINT demande_de_subvention_pkey PRIMARY KEY (id),
    CONSTRAINT demande_de_subvention_ukey UNIQUE (action_id),
    CONSTRAINT demande_de_subvention_action_id_fkey FOREIGN KEY (action_id) REFERENCES min.action(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT demande_de_subvention_createur_id_fkey FOREIGN KEY (createur_id) REFERENCES min.utilisateur(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT demande_de_subvention_enveloppe_financement_id_fkey FOREIGN KEY (enveloppe_financement_id) REFERENCES min.enveloppe_financement(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE min.demande_de_subvention OWNER TO min_scalingo;


CREATE TABLE min.beneficiaire_subvention (
    demande_de_subvention_id integer NOT NULL,
    membre_id text NOT NULL,
    CONSTRAINT beneficiaire_subvention_ukey UNIQUE (demande_de_subvention_id, membre_id),
    CONSTRAINT beneficiaire_subvention_demande_de_subvention_id_fkey FOREIGN KEY (demande_de_subvention_id) REFERENCES min.demande_de_subvention(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT beneficiaire_subvention_membre_id_fkey FOREIGN KEY (membre_id) REFERENCES min.membre(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE min.beneficiaire_subvention OWNER TO min_scalingo;


CREATE TABLE min.departement_enveloppe (
    departement_code text NOT NULL,
    enveloppe_id integer NOT NULL,
    plafond double precision NOT NULL,
    CONSTRAINT departement_enveloppe_ukey UNIQUE (departement_code, enveloppe_id),
    CONSTRAINT departement_enveloppe_departement_code_fkey FOREIGN KEY (departement_code) REFERENCES min.departement(code) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT departement_enveloppe_enveloppe_id_fkey FOREIGN KEY (enveloppe_id) REFERENCES min.enveloppe_financement(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE min.departement_enveloppe OWNER TO min_scalingo;


CREATE TABLE min.porteur_action (
    action_id integer NOT NULL,
    membre_id text NOT NULL,
    CONSTRAINT porteur_action_ukey UNIQUE (action_id, membre_id),
    CONSTRAINT porteur_action_action_id_fkey FOREIGN KEY (action_id) REFERENCES min.action(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT porteur_action_membre_id_fkey FOREIGN KEY (membre_id) REFERENCES min.membre(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

ALTER TABLE min.porteur_action OWNER TO min_scalingo;
