ALTER TABLE main.poste DROP COLUMN IF EXISTS etat_instruction;
ALTER TABLE main.poste ADD COLUMN IF NOT EXISTS etat_instruction_v1 CHARACTER VARYING,
ADD COLUMN IF NOT EXISTS etat_instruction_v2 CHARACTER VARYING;

ALTER TABLE main.subvention
ADD COLUMN IF NOT EXISTS avoir BIGINT,
ADD COLUMN IF NOT EXISTS cp_a_date BIGINT;
