DROP TABLE main.personne_structures_emplois CASCADE;
DROP TABLE main.personne_lieux_activites CASCADE;

CREATE TABLE main.personne_affectations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    personne_id INTEGER NOT NULL,
    structure_id INTEGER DEFAULT NULL,
    structure_coop_id UUID,
    mediateur_coop_id UUID,
    type CHARACTER VARYING NOT NULL CHECK (type IN ('structure_emploi', 'lieu_activite')),
    suppression TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    FOREIGN KEY (personne_id) REFERENCES main.personne(id),
    FOREIGN KEY (structure_id) REFERENCES main.structure(id)
);

-- Index unique comme contrainte d'unicité (impossibilité d'utiliser COALESCE dans la définition d'une contrainte).
CREATE UNIQUE INDEX personne_affectations_ukey ON main.personne_affectations (structure_coop_id, mediateur_coop_id, type, COALESCE(suppression, '1234-01-02 03:04:05'));

CREATE INDEX idx_personne_affectations_personne_id ON main.personne_affectations(personne_id);
CREATE INDEX idx_personne_affectations_structure_id ON main.personne_affectations(structure_id);

CREATE TRIGGER updated_at BEFORE UPDATE ON main.personne_affectations FOR EACH ROW EXECUTE FUNCTION updated_at_column();

-- Commentaires :
COMMENT ON TABLE main.personne_affectations IS 'Table de lien entre les personnes et les structures employeuses ou lieux d''activités.';
COMMENT ON COLUMN main.personne_affectations.type IS 'Type d''affectation personne <-> structure: structure_emploi ou lieu_activite.';
COMMENT ON COLUMN main.personne_affectations.suppression IS 'Date de suppression de l''affectation (NULL si en cours).';
