CREATE TABLE admin.icp_departement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    code CHARACTER VARYING(3) NOT NULL,
    label CHARACTER VARYING,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (id),
    CONSTRAINT icp_departement_code_ukey UNIQUE (code)
);

-- Create trigger for updated_at
CREATE TRIGGER admin_icp_departement_updated_at BEFORE UPDATE ON admin.icp_departement FOR EACH ROW EXECUTE PROCEDURE updated_at_column();

-- Add description to icp_commune table
COMMENT ON TABLE admin.icp_departement IS 'Table de gestion de l’indice de confiance des préfectures par département : https://pilote.modernisation.gouv.fr/';

COMMENT ON COLUMN admin.icp_departement.code IS E'Code département : un code à 2 ou 3 chiffres qui identifie \nle département français, en métropole ou en outre-mer.\nExemple : "13" pour les Bouches-du-Rhône.';
COMMENT ON COLUMN admin.icp_departement.label IS E'Appréciation qualitative de l’avancement des objectifs :\n'
' - OBJECTIFS SÉCURISÉS : les cibles sont déjà atteintes ou sécurisées.\n'
' - OBJECTIFS ATTEIGNABLES : les cibles sont en bonne voie d’être atteintes.\n'
' - APPUIS NÉCESSAIRES : des actions ou soutiens complémentaires sont requis.\n'
' - OBJECTIFS COMPROMIS : les cibles risquent fortement de ne pas être atteintes.\n'
' - Non renseignée : aucune appréciation n’a été saisie.';
