-- ============================================================
-- V068 – Refonte main.structure : créer main.structure_administrative
-- ============================================================
-- CONTEXTE :
-- Refonte de main.structure (cf docs/refonte-structure-plan.md, phase 1).
-- main.structure mélangeait deux concepts : entité légale employeuse
-- (= structure_administrative) et lieu physique d'inclusion (= lieu_inclusion).
-- Cette migration crée la nouvelle table structure_administrative, encore
-- vide à ce stade. Le peuplement se fera en phase 2 (V0xx+5).
--
-- DÉCISIONS ACTÉES (cf plan §"Décisions tranchées") :
--   - siret + ridet en colonnes séparées (nullable)
--   - PAS de CHECK obligatoire siret OR ridet (cas MIN sans ancrage SIRENE)
--   - contact JSONB conservé en héritage (dépréciation V047 non close ici)
--   - source non porté côté structure_administrative (= origine mednum-cli,
--     lieu uniquement)
--   - denomination_antenne : 2e composante d'unicité aux côtés de siret pour
--     supporter le pattern "grand réseau" (Emmaüs Connect, Reconnect Groupe
--     SOS, Petits Débrouillards…). Plusieurs antennes opérationnelles
--     partagent le SIRET du siège mais sont sémantiquement distinctes
--     (convention CoNum signée par le réseau, contrat de travail signé par
--     l'antenne). Cf décision tranchée 2026-05-25.
-- ============================================================

CREATE TABLE main.structure_administrative (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Colonne d'audit pour la transition (drop en phase 6).
    -- Trace l'id de main.structure qui a "donné naissance" à cette ligne après fusion par SIRET.
    -- Pour le mapping complet (toutes les lignes main.structure absorbées), faire une jointure par SIRET.
    old_main_structure_id INTEGER,

    -- Identité légale (au moins un des deux attendus, mais pas obligatoire)
    siret CHARACTER VARYING(14),
    ridet CHARACTER VARYING(10),
    denomination_sirene CHARACTER VARYING,
    rna CHARACTER VARYING(10),

    -- Discriminant pour le pattern "grand réseau" : plusieurs antennes
    -- partageant le même SIRET (= entité légale conventionnée) mais
    -- sémantiquement distinctes (cf commentaire en-tête, décision 2026-05-25).
    -- NULL = entité unique pour ce SIRET (cas standard).
    -- Sinon : nom legacy de l'antenne (Emmaüs Connect Évry, Emmaüs Connect
    -- Saint-Quentin, …).
    -- Aussi utilisé pour discriminer les structures sans SIRET (assos
    -- nationales : APF, Coop Num…) : leur denomination_antenne = leur nom
    -- pour respecter l'unicité.
    denomination_antenne CHARACTER VARYING(255),

    -- Adresse (siège SIRENE)
    adresse_id INTEGER,

    -- Identifiants cross-source (chacun UNIQUE)
    structure_coop_id UUID,
    structure_tp_id INTEGER,
    structure_ac_id UUID,

    -- Enrichissement SIRENE (autoritaire INSEE)
    etat_administratif CHARACTER VARYING,
    code_activite_principale CHARACTER VARYING(6),
    categorie_juridique CHARACTER VARYING(4) DEFAULT NULL,
    publique BOOLEAN,

    -- Spécifique Aidants Connect
    nb_mandats_ac INTEGER,

    -- Contact JSONB (héritage V047, dépréciation reportée — cf plan §Next N1)
    contact JSONB,

    -- Soft delete
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_by TEXT[],

    -- Audit & timestamps par source (cf V064 sur main.personne)
    edited_by CHARACTER VARYING(50),
    last_sirene_enrich_at DATE DEFAULT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at_coop TIMESTAMP WITHOUT TIME ZONE,
    updated_at_idposte TIMESTAMP WITHOUT TIME ZONE,
    updated_at_ac TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT structure_administrative_pkey PRIMARY KEY (id),

    -- Unicité des identifiants.
    -- (siret, denomination_antenne) UNIQUE NULLS NOT DISTINCT (pgsql 15+) :
    --   - (siret1, NULL) (siret1, NULL) => REJET (1 entité unique par SIRET sans antenne)
    --   - (siret1, "Évry") (siret1, "Saint-Quentin") => OK (antennes distinctes du même réseau)
    --   - (NULL, "APF") (NULL, "Coop Num") => OK (assos nationales sans SIRET, noms distincts)
    --   - (NULL, NULL) (NULL, NULL) => REJET (au plus 1 ligne complètement non identifiée)
    CONSTRAINT structure_administrative_siret_antenne_ukey
        UNIQUE NULLS NOT DISTINCT (siret, denomination_antenne),
    CONSTRAINT structure_administrative_ridet_ukey UNIQUE (ridet),
    CONSTRAINT structure_administrative_old_main_structure_id_ukey UNIQUE (old_main_structure_id),
    CONSTRAINT structure_administrative_structure_coop_id_ukey UNIQUE (structure_coop_id),
    CONSTRAINT structure_administrative_structure_ac_id_ukey UNIQUE (structure_ac_id),
    CONSTRAINT structure_administrative_structure_tp_id_ukey UNIQUE (structure_tp_id),

    -- Validation des formats
    CONSTRAINT structure_administrative_siret_format_check
        CHECK (siret IS NULL OR siret ~ '^\d{14}$'),
    CONSTRAINT structure_administrative_ridet_format_check
        CHECK (ridet IS NULL OR ridet ~ '^\d{7,10}$'),

    -- Foreign keys
    CONSTRAINT structure_administrative_adresse_fkey
        FOREIGN KEY (adresse_id) REFERENCES main.adresse (id),
    CONSTRAINT structure_administrative_categorie_juridique_fkey
        FOREIGN KEY (categorie_juridique) REFERENCES reference.categories_juridiques (code)
);

-- Trigger pour updated_at (pattern standard V004)
CREATE TRIGGER updated_at
    BEFORE UPDATE ON main.structure_administrative
    FOR EACH ROW EXECUTE FUNCTION updated_at_column();

-- Index sur les colonnes utiles aux requêtes API et MIN
CREATE INDEX structure_administrative_adresse_id_idx
    ON main.structure_administrative (adresse_id);

CREATE INDEX structure_administrative_denomination_sirene_idx
    ON main.structure_administrative (denomination_sirene);

-- Commentaires (deviennent doc API PostgREST si exposée plus tard)
COMMENT ON TABLE main.structure_administrative IS
  'Entité légale (identifiée par SIRET ou RIDET) qui peut employer des médiateurs, bénéficier de subventions, porter une gouvernance, héberger des lieux d''inclusion. Successeur de main.structure dans la refonte 2026 (cf docs/refonte-structure-plan.md).';

COMMENT ON COLUMN main.structure_administrative.siret IS
  'SIRET (métropole, 14 chiffres). NULL accepté pour les structures historiques MIN sans ancrage SIRENE.';

COMMENT ON COLUMN main.structure_administrative.ridet IS
  'RIDET (Nouvelle-Calédonie / Polynésie, 7-10 chiffres). NULL si non applicable.';

COMMENT ON COLUMN main.structure_administrative.denomination_antenne IS
  'Discriminant pour le pattern "grand réseau" (plusieurs antennes partageant le SIRET du siège : Emmaüs Connect, Reconnect Groupe SOS, Petits Débrouillards…). NULL = entité unique pour ce SIRET. Sinon nom legacy de l''antenne. Sert également de discriminant pour les SA sans SIRET (assos nationales).';

COMMENT ON COLUMN main.structure_administrative.contact IS
  'Contact JSONB hérité de main.structure (référent nommé : nom, prenom, courriels, telephone). Dépréciation V047 vers main.contact + main.contact_structure_administrative non close par cette refonte (cf plan §Next N1).';

COMMENT ON COLUMN main.structure_administrative.edited_by IS
  'Marqueur de la source d''écriture : coop, id-poste, aidants-connect, carto, min.';

COMMENT ON COLUMN main.structure_administrative.deleted_by IS
  'Liste cumulative des sources ayant marqué la suppression (V033 pattern).';

COMMENT ON COLUMN main.structure_administrative.old_main_structure_id IS
  'Audit / mapping pendant la transition refonte : id de la ligne main.structure choisie lors de la fusion par SIRET (cf phase 2). À dropper en phase 6 quand main.structure est supprimée. Pour le mapping complet des lignes absorbées par fusion, joindre via siret.';
