-- ============================================================
-- V069 – Refonte main.structure : créer main.lieu_inclusion
-- ============================================================
-- CONTEXTE :
-- Cf docs/refonte-structure-plan.md, phase 1. Successeur partiel de
-- main.structure pour le concept "lieu physique d'inclusion numérique"
-- (bibliothèque, France Services, médiathèque…). La table est vide à ce
-- stade. Peuplement en phase 2 depuis les structures actuellement
-- catégorisées "pure lieu" ou "mixte".
--
-- DÉCISIONS ACTÉES :
--   - Clé naturelle UNIQUE : structure_cartographie_nationale_id (Q2)
--   - contact JSONB conservé (choix sémantique : coordonnées publiques
--     anonymes — telephone, courriels, site_web)
--   - adresse_id nullable (cas existants : ~72 lieux carto sans adresse
--     résolue, on les tolère plutôt que de bloquer le peuplement phase 2)
--   - Champs catégories métier intégralement repris depuis main.structure
-- ============================================================

CREATE TABLE main.lieu_inclusion (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Colonne d'audit pour la transition (drop en phase 6).
    -- Trace l'id de main.structure d'origine (1 ligne main.structure → 1 lieu_inclusion).
    old_main_structure_id INTEGER,

    -- Identité
    nom CHARACTER VARYING(255) NOT NULL,
    adresse_id INTEGER,

    -- Identifiant cartographie nationale (seule clé naturelle externe)
    structure_cartographie_nationale_id CHARACTER VARYING,
    visible_pour_cartographie_nationale BOOLEAN,
    fiche_acces_libre CHARACTER VARYING,

    -- Présentation et accueil
    presentation_resume TEXT,
    presentation_detail TEXT,
    horaires CHARACTER VARYING,
    prise_rdv CHARACTER VARYING,
    itinerance TEXT[],

    -- Services proposés
    services TEXT[],
    modalites_acces TEXT[],
    modalites_accompagnement TEXT[],

    -- Publics et frais
    publics_specifiquement_adresses TEXT[],
    prise_en_charge_specifique TEXT[],
    frais_a_charge TEXT[],

    -- Formations et dispositifs
    formations_labels TEXT[],
    autres_formations_labels TEXT[],
    dispositif_programmes_nationaux TEXT[],

    -- Typologie (peut être héritée de la structure_administrative associée)
    typologies TEXT[],

    -- Contact JSONB (coordonnées publiques anonymes du lieu)
    contact JSONB,

    -- Compteurs Coop
    mediateurs_en_activite INTEGER,
    emplois INTEGER,

    -- Audit
    source CHARACTER VARYING,
    edited_by CHARACTER VARYING(50),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT lieu_inclusion_pkey PRIMARY KEY (id),

    -- Unicité de l'identifiant carto et de l'audit
    CONSTRAINT lieu_inclusion_carto_id_ukey
        UNIQUE (structure_cartographie_nationale_id),
    CONSTRAINT lieu_inclusion_old_main_structure_id_ukey
        UNIQUE (old_main_structure_id),

    -- FK adresse
    CONSTRAINT lieu_inclusion_adresse_fkey
        FOREIGN KEY (adresse_id) REFERENCES main.adresse (id)
);

CREATE TRIGGER updated_at
    BEFORE UPDATE ON main.lieu_inclusion
    FOR EACH ROW EXECUTE FUNCTION updated_at_column();

CREATE INDEX lieu_inclusion_adresse_id_idx
    ON main.lieu_inclusion (adresse_id);

CREATE INDEX lieu_inclusion_nom_idx
    ON main.lieu_inclusion (nom);

CREATE INDEX lieu_inclusion_visible_idx
    ON main.lieu_inclusion (visible_pour_cartographie_nationale)
    WHERE visible_pour_cartographie_nationale = TRUE;

COMMENT ON TABLE main.lieu_inclusion IS
  'Lieu physique d''inclusion numérique (bibliothèque, France Services, médiathèque, EPN…). Successeur de main.structure pour ce concept dans la refonte 2026 (cf docs/refonte-structure-plan.md).';

COMMENT ON COLUMN main.lieu_inclusion.structure_cartographie_nationale_id IS
  'Identifiant mednum-cli du lieu — seule clé naturelle externe garantie (pas de SIRET côté lieu, le SIRET appartient à la structure_administrative liée par asso).';

COMMENT ON COLUMN main.lieu_inclusion.contact IS
  'Coordonnées publiques anonymes du lieu (telephone, courriels, site_web). Sémantiquement distinct du contact JSONB côté structure_administrative qui contient des référents nommés.';

COMMENT ON COLUMN main.lieu_inclusion.source IS
  'Origine mednum-cli (Hinaura, Fredo, Paca, Paris, Coop numérique…). Spécifique au lieu, ne s''applique pas à la structure_administrative.';

COMMENT ON COLUMN main.lieu_inclusion.old_main_structure_id IS
  'Audit / mapping pendant la transition refonte : id de la ligne main.structure d''origine (1:1, pas de fusion côté lieu). À dropper en phase 6.';
