-- ============================================================
-- V070 – Refonte main.structure : table d'asso lieu ⋈ structure
-- ============================================================
-- CONTEXTE :
-- Cf docs/refonte-structure-plan.md, phase 1. Table d'association entre
-- un lieu d'inclusion (lieu physique) et la / les structure(s)
-- administrative(s) qui le portent (employeur, porteur de gouvernance,
-- gestionnaire). Un lieu peut être hébergé par plusieurs structures
-- administratives (cas multi-porteurs : France Services porté à la fois
-- par La Poste et l'agglo). Une structure administrative peut héberger
-- plusieurs lieux.
--
-- DÉCISIONS ACTÉES :
--   - Pas de colonne 'type' (porteur vs gestionnaire) au MVP — Q3 reportée
--   - Asso facultative (Q4) : un lieu peut exister sans structure_administrative
--     identifiée (cas carto orphelin), une structure_administrative peut
--     exister sans lieu (cas pures employeuses comme idposte)
-- ============================================================

CREATE TABLE main.lieu_inclusion_structure_administrative (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    lieu_id INTEGER NOT NULL,
    structure_administrative_id INTEGER NOT NULL,
    edited_by CHARACTER VARYING(50),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT lieu_inclusion_structure_administrative_pkey PRIMARY KEY (id),

    CONSTRAINT lieu_inclusion_structure_administrative_ukey
        UNIQUE (lieu_id, structure_administrative_id),

    CONSTRAINT lieu_inclusion_structure_administrative_lieu_fkey
        FOREIGN KEY (lieu_id) REFERENCES main.lieu_inclusion (id)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT lieu_inclusion_structure_administrative_admin_fkey
        FOREIGN KEY (structure_administrative_id)
        REFERENCES main.structure_administrative (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TRIGGER updated_at
    BEFORE UPDATE ON main.lieu_inclusion_structure_administrative
    FOR EACH ROW EXECUTE FUNCTION updated_at_column();

CREATE INDEX lieu_inclusion_structure_administrative_lieu_id_idx
    ON main.lieu_inclusion_structure_administrative (lieu_id);

CREATE INDEX lieu_inclusion_structure_administrative_admin_id_idx
    ON main.lieu_inclusion_structure_administrative (structure_administrative_id);

COMMENT ON TABLE main.lieu_inclusion_structure_administrative IS
  'Association N:N entre lieu_inclusion et structure_administrative. Un lieu peut être porté par plusieurs structures administratives, une structure administrative peut héberger plusieurs lieux. Asso facultative (lieu sans structure ou inverse acceptés).';
