-- ============================================================
-- V071 – Refonte main.structure : personne_affectations_emploi
-- ============================================================
-- CONTEXTE :
-- Cf docs/refonte-structure-plan.md, phase 1. Successeur de la moitié
-- "structure_emploi" de main.personne_affectations. Lie une personne
-- à une structure_administrative pour exprimer une relation d'emploi
-- (employeur ↔ employé).
--
-- DÉCISIONS ACTÉES :
--   - 2 tables séparées au lieu d'une avec type discriminator (Q8)
--   - Source = coop / idposte / aidants-connect (V042 pattern)
--   - est_active = TRUE/FALSE (V043 pattern, remplace suppression)
--   - Clé unique métier : (personne_id, structure_administrative_id, source)
-- ============================================================

CREATE TABLE main.personne_affectations_emploi (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    personne_id INTEGER NOT NULL,
    structure_administrative_id INTEGER NOT NULL,
    source CHARACTER VARYING NOT NULL
        CHECK (source IN ('idposte', 'aidants-connect', 'coop', 'min')),
    est_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT personne_affectations_emploi_pkey PRIMARY KEY (id),

    CONSTRAINT personne_affectations_emploi_personne_fkey
        FOREIGN KEY (personne_id) REFERENCES main.personne (id),

    CONSTRAINT personne_affectations_emploi_admin_fkey
        FOREIGN KEY (structure_administrative_id)
        REFERENCES main.structure_administrative (id)
);

-- Clé unique métier : 1 ligne par (personne, structure_administrative, source)
CREATE UNIQUE INDEX personne_affectations_emploi_ukey
    ON main.personne_affectations_emploi (personne_id, structure_administrative_id, source);

CREATE INDEX idx_personne_affectations_emploi_personne_id
    ON main.personne_affectations_emploi (personne_id);

CREATE INDEX idx_personne_affectations_emploi_structure_administrative_id
    ON main.personne_affectations_emploi (structure_administrative_id);

CREATE INDEX idx_personne_affectations_emploi_active
    ON main.personne_affectations_emploi (structure_administrative_id, est_active)
    WHERE est_active = TRUE;

CREATE TRIGGER updated_at
    BEFORE UPDATE ON main.personne_affectations_emploi
    FOR EACH ROW EXECUTE FUNCTION updated_at_column();

COMMENT ON TABLE main.personne_affectations_emploi IS
  'Relations d''emploi entre une personne et une structure_administrative (employeur ↔ employé). Successeur du type=structure_emploi de main.personne_affectations dans la refonte 2026.';

COMMENT ON COLUMN main.personne_affectations_emploi.source IS
  'Source d''écriture de l''affectation : idposte (CSV CoNum), aidants-connect (API AC), coop (API Coop), min (création MIN).';

COMMENT ON COLUMN main.personne_affectations_emploi.est_active IS
  'TRUE si la relation d''emploi est active (employé en poste). FALSE si résiliée (historique).';
