-- ============================================================
-- V072 – Refonte main.structure : personne_affectations_lieu
-- ============================================================
-- CONTEXTE :
-- Cf docs/refonte-structure-plan.md, phase 1. Successeur de la moitié
-- "lieu_activite" de main.personne_affectations. Lie une personne à un
-- lieu_inclusion pour exprimer une relation de présence sur le lieu
-- (le médiateur travaille / intervient sur ce lieu).
--
-- DÉCISIONS ACTÉES :
--   - 2 tables séparées au lieu d'une avec type discriminator (Q8)
--   - Source = coop / aidants-connect (idposte ne pose pas de lieu)
--   - est_active = TRUE/FALSE (V043 pattern)
--   - Clé unique métier : (personne_id, lieu_id, source)
-- ============================================================

CREATE TABLE main.personne_affectations_lieu (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    personne_id INTEGER NOT NULL,
    lieu_id INTEGER NOT NULL,
    source CHARACTER VARYING NOT NULL
        CHECK (source IN ('coop', 'aidants-connect', 'carto', 'min')),
    est_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT personne_affectations_lieu_pkey PRIMARY KEY (id),

    CONSTRAINT personne_affectations_lieu_personne_fkey
        FOREIGN KEY (personne_id) REFERENCES main.personne (id),

    CONSTRAINT personne_affectations_lieu_lieu_fkey
        FOREIGN KEY (lieu_id) REFERENCES main.lieu_inclusion (id)
);

-- Clé unique métier : 1 ligne par (personne, lieu, source)
CREATE UNIQUE INDEX personne_affectations_lieu_ukey
    ON main.personne_affectations_lieu (personne_id, lieu_id, source);

CREATE INDEX idx_personne_affectations_lieu_personne_id
    ON main.personne_affectations_lieu (personne_id);

CREATE INDEX idx_personne_affectations_lieu_lieu_id
    ON main.personne_affectations_lieu (lieu_id);

CREATE INDEX idx_personne_affectations_lieu_active
    ON main.personne_affectations_lieu (lieu_id, est_active)
    WHERE est_active = TRUE;

CREATE TRIGGER updated_at
    BEFORE UPDATE ON main.personne_affectations_lieu
    FOR EACH ROW EXECUTE FUNCTION updated_at_column();

COMMENT ON TABLE main.personne_affectations_lieu IS
  'Relations de présence d''une personne sur un lieu_inclusion (médiateur intervient / travaille sur le lieu). Successeur du type=lieu_activite de main.personne_affectations dans la refonte 2026.';

COMMENT ON COLUMN main.personne_affectations_lieu.source IS
  'Source d''écriture : coop (API Coop), aidants-connect (rare, principalement employeuse), carto (lien implicite avec lieu), min.';

COMMENT ON COLUMN main.personne_affectations_lieu.est_active IS
  'TRUE si le médiateur intervient actuellement sur ce lieu. FALSE si historique.';
