-- V152 : table d'appariements lieux ↔ records du fichier national mednum
-- (SEPT #1724, étape 3 — matching maison). Alimentée par le DAG
-- lieu-appariement (même famille que personne-reconciliation / N13).
--
-- Rôle : mémoire durable du rapprochement coop ↔ sources externes. Le silver
-- carto est reconstruit à chaque run (TRUNCATE) et les ids composites mednum
-- sont recomposés à chaque fusion : toute connaissance durable doit vivre
-- ici. Deux méthodes :
--   - 'segment_coop' : preuve par les segments d'id — un record fusionné
--     « Coop-numérique_<uuid>__France-Services_789 » prouve que le segment
--     France-Services_789 décrit le lieu coop <uuid>. Cette mémoire survit
--     au retrait de la coop des sources mednum (le record redevenu
--     « France-Services_789 » reste rattaché au lieu).
--   - 'similarite' : candidats détectés par score (nom/adresse/distance,
--     seuil 83 repris de mednum-cli inter-sources) entre records purement
--     externes et lieux coop → file de revue humaine (les ~360 doublons
--     non fusionnés).
--
-- Clé de mémoire = le SEGMENT d'id (id par source, stable entre les
-- recompositions), pas l'id composite complet : un rejet humain survit au
-- churn des ids. Le record complet est snapshoté (carto_record_id,
-- carto_nom/adresse/commune) pour l'affichage, sans dépendre du silver.
--
-- Cycle de vie des statuts :
--   auto      : preuve par segment (fusion mednum) — pas de revue requise
--   a_valider : candidat par similarité, en attente de revue humaine
--   valide    : confirmé par un humain (decide_par / decide_le)
--   rejete    : infirmé par un humain — JAMAIS écrasé par les runs suivants
--     (sans cette mémoire, les candidats re-remonteraient à chaque run)
--
-- lieu_id : pas de FK vers main.lieu_inclusion — la table doit survivre à la
-- bascule de lieu_inclusion en vue (étape 5 du plan, cf. ticket) ; les
-- lignes orphelines sont nettoyées par le DAG.

CREATE TABLE main.lieu_appariement (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carto_segment text NOT NULL,
    lieu_id integer NOT NULL,
    carto_record_id text NOT NULL,
    source text,
    methode varchar(20) NOT NULL
        CHECK (methode IN ('segment_coop', 'similarite')),
    statut varchar(20) NOT NULL DEFAULT 'a_valider'
        CHECK (statut IN ('auto', 'a_valider', 'valide', 'rejete')),
    score_nom smallint,
    score_adresse smallint,
    score_distance smallint,
    score_global smallint,
    distance_m integer,
    carto_nom text,
    carto_adresse text,
    carto_commune text,
    premiere_detection timestamp NOT NULL DEFAULT now(),
    derniere_detection timestamp NOT NULL DEFAULT now(),
    decide_par varchar(255),
    decide_le timestamp,
    CONSTRAINT lieu_appariement_ukey UNIQUE (carto_segment, lieu_id)
);

CREATE INDEX lieu_appariement_lieu_idx ON main.lieu_appariement (lieu_id);
CREATE INDEX lieu_appariement_a_valider_idx ON main.lieu_appariement (statut)
    WHERE statut = 'a_valider';

COMMENT ON TABLE main.lieu_appariement IS
    'Mémoire du rapprochement lieux coop ↔ records mednum (V152, SEPT #1724). '
    'Clé = segment d''id mednum (stable) × lieu. methode : segment_coop '
    '(preuve par fusion) / similarite (candidat scoré). statut : auto / '
    'a_valider / valide / rejete — les décisions humaines (valide, rejete) '
    'ne sont jamais écrasées par les runs.';
COMMENT ON COLUMN main.lieu_appariement.carto_segment IS
    'Segment de l''id composite mednum (= id du record chez sa source, '
    'stable entre les recompositions de fusion).';
COMMENT ON COLUMN main.lieu_appariement.carto_record_id IS
    'Dernier id composite complet observé portant ce segment (snapshot).';
COMMENT ON COLUMN main.lieu_appariement.derniere_detection IS
    'Dernier run du DAG lieu-appariement où la paire était observable dans '
    'le silver — une paire absente n''est PAS supprimée (mémoire).';

-- File de revue humaine (pattern N13 : liste dataviz consommée par Metabase).
CREATE VIEW dataviz.lieu_appariements_a_valider AS
SELECT la.id,
       la.carto_segment,
       la.carto_record_id,
       la.source,
       la.carto_nom,
       la.carto_adresse,
       la.carto_commune,
       la.score_nom,
       la.score_adresse,
       la.score_distance,
       la.score_global,
       la.distance_m,
       la.premiere_detection,
       la.derniere_detection,
       l.id AS lieu_id,
       l.nom AS lieu_nom,
       a.numero_voie AS lieu_numero_voie,
       a.nom_voie AS lieu_nom_voie,
       a.nom_commune AS lieu_commune,
       a.code_insee AS lieu_code_insee
FROM main.lieu_appariement la
JOIN main.lieu_inclusion l ON l.id = la.lieu_id
LEFT JOIN main.adresse a ON a.id = l.adresse_id
WHERE la.statut = 'a_valider';

COMMENT ON VIEW dataviz.lieu_appariements_a_valider IS
    'File de revue humaine des candidats d''appariement lieu coop ↔ record '
    'externe (V152, SEPT #1724) : score >= 83, à valider ou rejeter dans '
    'main.lieu_appariement (statut + decide_par + decide_le).';

DO $grants$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_metabase') THEN
        GRANT SELECT ON dataviz.lieu_appariements_a_valider TO app_metabase;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nao_ro') THEN
        GRANT SELECT ON main.lieu_appariement TO nao_ro;
    END IF;
END
$grants$;
